### ISSUE TITLE
after installing aurelia-cli v 0.2.0 I can't run any command-Cannot find module 'concat-map'

### ISSUE THREAD

**Issue by capaj** [aurelia/cli#107]
This is the error I get on my win 8.1 64 bit machine
```
warn: Local aurelia installation not found!
module.js:334
    throw err;
          ^
Error: Cannot find module 'concat-map'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:282:25)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\capaj_000\AppData\Roaming\npm\node_modules\a
urelia-cli\node_modules\download-github-repo\node_modules\download\node_modules\
decompress\node_modules\rimraf\node_modules\glob\node_modules\minimatch\node_mod
ules\brace-expansion\index.js:1:79)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\capaj_000\AppData\Roaming\npm\node_modules\a
urelia-cli\node_modules\download-github-repo\node_modules\download\node_modules\
decompress\node_modules\rimraf\node_modules\glob\node_modules\minimatch\minimatc
h.js:10:14)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)

c:\WebstormProjects\aurelia-mocha-boilerplate>
```

**Comment by ahmedshuhel** [comment]
@capaj what command are you trying to run? `aurelia new` ?

**Comment by capaj** [comment]
@ahmedshuhel I tried 
```
aurelia new
aurelia
aurelia init
```
seems to be crashing in a code, which runs for any command.

**Comment by ahmedshuhel** [comment]
I believe we are not using `concat-map` anywhere. It may be a dependency of any of the module we are using. Let us check please. We will let you know as soon as we get something substantial.

**Comment by capaj** [comment]
@ahmedshuhel this error is thrown from `brace-expansion/index.js:1:79` but it shouldn't throw because the concat-map package is there available. One thing that comes to my mind, is that this is cause by a bad handling of such a long path on Windows. I will test on linux first chance I get.

**Comment by ahmedshuhel** [comment]
@capaj We have a new release now. Could you try it and see if it still exists?
