### ISSUE TITLE
"Unbundle" is broken

### ISSUE THREAD

**Issue by shabalin** [aurelia/cli#153]
bundle command works for me, but if I try to unbundle (just to revert affected config.js and index.html) I get this error 
```
$ aurelia unbundle
info: Un bundling ...
/Users/pavel/work/proto/node_modules/aurelia-cli/dist/lib/unbundler.js:49
  _jspm2['default'].setPackagePath(opts.packagePath);
                                       ^
TypeError: Cannot read property 'packagePath' of undefined
    at unbundle (/Users/pavel/work/proto/node_modules/aurelia-cli/dist/lib/unbundler.js:49:40)
    at InitCommand.action (/Users/pavel/work/proto/node_modules/aurelia-cli/dist/commands/unbundle.js:47:34)
    at Command.listener (/Users/pavel/work/proto/node_modules/aurelia-cli/node_modules/commander/index.js:301:8)
    at Command.emit (events.js:110:17)
    at Command.parseArgs (/Users/pavel/work/proto/node_modules/aurelia-cli/node_modules/commander/index.js:610:12)
    at Command.parse (/Users/pavel/work/proto/node_modules/aurelia-cli/node_modules/commander/index.js:458:21)
    at Aurelia.run (/Users/pavel/work/proto/node_modules/aurelia-cli/dist/index.js:122:30)
    at /usr/local/lib/node_modules/aurelia-cli/bin/aurelia.js:77:13
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

aurelia-cli version `latest: '0.3.1'`

**Comment by stoffeastrom** [comment]
Did you add the `unbundle` command?

See latest `skeleton-navigation` example

https://github.com/aurelia/skeleton-navigation/blob/master/aureliafile.js#L33-L34

**Comment by shabalin** [comment]
that helped, thanks!
