### ISSUE TITLE
Custom element  i app-bundle.js cant be found...

### ISSUE THREAD

**Issue by SorenMuller** [aurelia/cli#207]
Hi,

I cant seem to add any custom elements when using bundles.. 
Simple to reproduce..

1.Make new app using aurelia-cli
2. using aurelia-cli generate custom element, let call it 'thingy'
3. add new element to index.ts in resources folder
    
    export function configure(config: FrameworkConfiguration) 
    {
         config.globalResources([ "elements/thingy"]);  
    }

4. 4 add new element to any html page

Builds without error, but gives the error below in  chrome..

```
vendor-bundle.js:3688 GET http://localhost:9000/src/elements/thingy.js g.load @ vendor-bundle.js:3688load @ vendor-bundle.js:3683load @ vendor-bundle.js:3671fetch @ vendor-bundle.js:3671check @ vendor-bundle.js:3671enable @ vendor-bundle.js:3677enable @ vendor-bundle.js:3681(anonymous function) @ vendor-bundle.js:3676(anonymous function) @ vendor-bundle.js:3661y @ vendor-bundle.js:3660enable @ vendor-bundle.js:3675init @ vendor-bundle.js:3670(anonymous function) @ vendor-bundle.js:3680
vendor-bundle.js:1335 Unhandled rejection Error: Script error for "elements/thingy"
http://requirejs.org/docs/errors.html#scripterror
    at Error (native)
    at F (http://localhost:9000/scripts/vendor-bundle.js:3661:290)
    at HTMLScriptElement.onScriptError (http://localhost:9000/scripts/vendor-bundle.js:3684:113)
From previous event:
    at DefaultLoader.loadModule (http://localhost:9000/scripts/vendor-bundle.js:10657:14)
    at DefaultLoader.loadAllModules (http://localhost:9000/scripts/vendor-bundle.js:10604:25)
    at ViewEngine.importViewResources (http://localhost:9000/scripts/vendor-bundle.js:22022:26)
    at http://localhost:9000/scripts/vendor-bundle.js:10105:25
From previous event:
    at loadResources (http://localhost:9000/scripts/vendor-bundle.js:10096:9)
    at http://localhost:9000/scripts/vendor-bundle.js:10173:16
    at next (http://localhost:9000/scripts/vendor-bundle.js:10053:32)
    at runTasks (http://localhost:9000/scripts/vendor-bundle.js:10059:12)
    at http://localhost:9000/scripts/vendor-bundle.js:10334:18
From previous event:
    at http://localhost:9000/scripts/vendor-bundle.js:10333:23
From previous event:
    at FrameworkConfiguration.apply (http://localhost:9000/scripts/vendor-bundle.js:10319:44)
    at Aurelia.start (http://localhost:9000/scripts/vendor-bundle.js:9948:23)
    at Object.configure (http://localhost:9000/scripts/app-bundle.js:38:17)
    at http://localhost:9000/scripts/vendor-bundle.js:9768:29
From previous event:
    at config (http://localhost:9000/scripts/vendor-bundle.js:9767:48)
    at handleApp (http://localhost:9000/scripts/vendor-bundle.js:9759:12)
    at http://localhost:9000/scripts/vendor-bundle.js:9787:13
From previous event:
    at http://localhost:9000/scripts/vendor-bundle.js:9785:40
From previous event:
    at http://localhost:9000/scripts/vendor-bundle.js:9784:29
From previous event:
    at run (http://localhost:9000/scripts/vendor-bundle.js:9780:26)
    at Object.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:9807:3)
    at Object.execCb (http://localhost:9000/scripts/vendor-bundle.js:3683:299)
    at Object.check (http://localhost:9000/scripts/vendor-bundle.js:3672:50)
    at Object.enable (http://localhost:9000/scripts/vendor-bundle.js:3677:58)
    at Object.enable (http://localhost:9000/scripts/vendor-bundle.js:3681:433)
    at Object.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:3676:436)
    at http://localhost:9000/scripts/vendor-bundle.js:3661:140
    at y (http://localhost:9000/scripts/vendor-bundle.js:3660:207)
    at Object.enable (http://localhost:9000/scripts/vendor-bundle.js:3675:469)
    at Object.init (http://localhost:9000/scripts/vendor-bundle.js:3670:154)
    at http://localhost:9000/scripts/vendor-bundle.js:3680:308
```

**Comment by kuechlerm** [comment]
I leave the resources/index.ts as is and have no problems.

```
export function configure(config: FrameworkConfiguration) {
  //config.globalResources([]);  
}
```

**Comment by EisenbergEffect** [comment]
You need to use a relative url, relative to the index.ts:

```javascript
export function configure(config: FrameworkConfiguration) 
{
     config.globalResources('./elements/thingy');  
}
```
