### ISSUE TITLE
CLI Command "au generate resource" Not Working

### ISSUE THREAD

**Issue by jwuliger** [aurelia/cli#258]
**I'm submitting a bug report**

* **Library Version:**

1. **cli** 0.17.0
2. **aurelia** 1.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10 Enterprise

* **Node Version:**
4.4.7 LTS

* **NPM Version:**
3.10.6

* **Browser:**
N/A

* **Language:**
TypeScript 2.0.0

**Current behavior:**
After generating a new project using `au new` I tried to use the Generator feature. No changes were made to the scaffold project.

Using the "generate" command for the CLI throws this error: `Invalid Command: generate`

**Full Error**
`
Inner Error:
Message: Path must be a string. Received undefined
Inner Error Stack:
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.join (path.js:221:5)
    at new <anonymous> (C:\Users\jwuliger\AppData\Roaming\npm\node_modules\aurelia-cli\lib\project.js:23:31)
    at Object.invoke (C:\Users\jwuliger\AppData\Roaming\npm\node_modules\aurelia-cli\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:415:12)
    at InvocationHandler.invoke (C:\Users\jwuliger\AppData\Roaming\npm\node_modules\aurelia-cli\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:392:166)
    at Container.invoke (C:\Users\jwuliger\AppData\Roaming\npm\node_modules\aurelia-cli\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:654:23)
    at StrategyResolver.get (C:\Users\jwuliger\AppData\Roaming\npm\node_modules\aurelia-cli\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:133:35)
    at Container.get (C:\Users\jwuliger\AppData\Roaming\npm\node_modules\aurelia-cli\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:591:21)
    at Optional.get (C:\Users\jwuliger\AppData\Roaming\npm\node_modules\aurelia-cli\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:89:24)
    at Container.get (C:\Users\jwuliger\AppData\Roaming\npm\node_modules\aurelia-cli\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:578:18)
End Inner Error Stack
`

**Expected/desired behavior:**

Just run any au generate command from the documentation.

**Comment by BBosman** [comment]
Did you `cd` into the generated directory after running `au new`?

If you don't do that you I get the error message you had as well.

**Comment by jwuliger** [comment]
@BBosman That must have been it. I just created a new project, then closed the command prompt and started a fresh one. Doing that and then calling `au generate X` worked! It seems to be when you `cd `into the new project.

**Comment by samuelmolinski** [comment]
I just ran across this issue too.  Since this is more of a user issue, could we get a more helpful error message reminding us to be in the project folder?  Thanks.

**Comment by DSTechLabs** [comment]
**au run** is also an Invalid Command ???

**Comment by jwuliger** [comment]
@dstechlabs How are you using au run?

**Comment by EisenbergEffect** [comment]
You need to be inside a project folder. Make sure you are in a project.

**Comment by DSTechLabs** [comment]
I created a new project with au new ...
Moved into the new project folder
Then tried both au build and au run.
?
![au run](https://cloud.githubusercontent.com/assets/18746108/17710934/87dead9c-63bd-11e6-9451-7d1057813893.jpg)

**Comment by DSTechLabs** [comment]
Also, using Firefox to open the index.html - "Hello World" not showing.

**Comment by MikeGitIt** [comment]
I am also unable to run au run nor au build - invalid command error and then it displays the usage information. just as you see in the screenshot which DSTechLabs provided.  My environment, at the time of this post:

Windows 7 (work requires I not upgrade to 10, for whatever reason)
Babun Terminal - Emulates BASH/ZSH using cygwin - I know, you want to ask, "Why though?", but it's my situation at the moment, work with me here.

I have node version 4.4.3 running

I am running Git 2.1.4

I also have JSPM installed - per Rob's youtube demo

Okay, that's all I have to offer at the moment.

**Comment by EisenbergEffect** [comment]
This may be an issue related to NPM. We've seen some npm install issues cause this. You would need to clear your system's npm cache and install again. Then make sure to be in the project folder after you create a project to run the additional commands. We have this issue documented in a troubleshooting section of the docs going out soon.

**Comment by jiger25783** [comment]
what do i have to install again? node or au cli?
