### ISSUE TITLE
ENOENT error when building with prod environment flag

### ISSUE THREAD

**Issue by Ashthos** [aurelia/cli#377]
**I'm submitting a bug report**

* **Library Version:**
0.18.0   `au --version`

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.3.1

* **NPM Version:**
3.10.3

* **Language:**
TypeScript 2.0.2

**Current behavior:**
`au build --env prod` crashes with the following

```
Tracing dialogs/credit-note-cancel-dialog...
{ uid: 9,
  name: 'writeBundles',
  branch: false,
  error:
   { Error: ENOENT: no such file or directory, open 'D:\Code\Apps\my-app\src\aurelia-dialog.js'
       at Error (native)
       at Object.fs.openSync (fs.js:640:18)
       at Object.fs.readFileSync (fs.js:508:33)
       at Object.exports.readFileSync (D:\Code\Apps\my-app\node_modules\aurelia-cli\lib\file-system.js:38:13)
       at amodroTrace.fileRead (D:\Code\Apps\my-app\node_modules\aurelia-cli\lib\build\bundled-source.js:83:31)
       at Object.context.fileRead (D:\Code\Apps\my-app\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:176:18)
       at Object.context.load (D:\Code\Apps\my-app\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:357:30)
       at Object.Module.load (eval at <anonymous> (D:\Code\Apps\my-app\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:832:29)
       at Object.Module.fetch (eval at <anonymous> (D:\Code\Apps\my-app\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:822:66)
       at Object.Module.check (eval at <anonymous> (D:\Code\Apps\my-app\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:854:30)
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'D:\\Code\\Apps\\my-app\\src\\aurelia-dialog.js',
     moduleTree: [ 'dialogs/credit-note-cancel-dialog' ],
     fileName: 'D:/Code/Apps/my-app/src/dialogs/credit-note-cancel-dialog.js' },
  duration: [ 4, 90866245 ],
  time: 1476653760535 }
{ uid: 0,
  name: '<series>',
  branch: true,
  error:
   { Error: ENOENT: no such file or directory, open 'D:\Code\Apps\my-app\src\aurelia-dialog.js'
       at Error (native)
       at Object.fs.openSync (fs.js:640:18)
       at Object.fs.readFileSync (fs.js:508:33)
       at Object.exports.readFileSync (D:\Code\Apps\my-app\node_modules\aurelia-cli\lib\file-system.js:38:13)
       at amodroTrace.fileRead (D:\Code\Apps\my-app\node_modules\aurelia-cli\lib\build\bundled-source.js:83:31)
       at Object.context.fileRead (D:\Code\Apps\my-app\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:176:18)
       at Object.context.load (D:\Code\Apps\my-app\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:357:30)
       at Object.Module.load (eval at <anonymous> (D:\Code\Apps\my-app\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:832:29)
       at Object.Module.fetch (eval at <anonymous> (D:\Code\Apps\my-app\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:822:66)
       at Object.Module.check (eval at <anonymous> (D:\Code\Apps\my-app\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:854:30)
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'D:\\Code\\Apps\\my-app\\src\\aurelia-dialog.js',
     moduleTree: [ 'dialogs/credit-note-cancel-dialog' ],
     fileName: 'D:/Code/Apps/my-app/src/dialogs/credit-note-cancel-dialog.js' },
  duration: [ 7, 891327163 ],
  time: 1476653760574 }
{ Error: ENOENT: no such file or directory, open 'D:\Code\Apps\my-app\src\aurelia-dialog.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.exports.readFileSync (D:\Code\Apps\my-app\node_modules\aurelia-cli\lib\file-system.js:38:13)
    at amodroTrace.fileRead (D:\Code\Apps\my-app\node_modules\aurelia-cli\lib\build\bundled-source.js:83:31)
    at Object.context.fileRead (D:\Code\Apps\my-app\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:176:18)
    at Object.context.load (D:\Code\Apps\my-app\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:357:30)
    at Object.Module.load (eval at <anonymous> (D:\Code\Apps\my-app\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:832:29)
    at Object.Module.fetch (eval at <anonymous> (D:\Code\Apps\my-app\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:822:66)
    at Object.Module.check (eval at <anonymous> (D:\Code\Apps\my-app\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:854:30)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\Code\\Apps\\my-app\\src\\aurelia-dialog.js',
  moduleTree: [ 'dialogs/credit-note-cancel-dialog' ],
  fileName: 'D:/Code/Apps/my-app/src/dialogs/credit-note-cancel-dialog.js' }
```

where ` credit-note-cancel-dialog.ts ` contains

```
import { inject } from 'aurelia-framework';
import { DialogController } from 'aurelia-dialog';

@inject(DialogController)
export class CreditNoteCancelDialog {
    public objectIdentifier: string;

    constructor(private dialogController: DialogController){
    }

    activate(model) {
        this.objectIdentifier = model.objectIdentifier
    }

    confirm() {
        this.dialogController.ok();
    }

    cancel() {
        this.dialogController.cancel();
    }
}
```

**Expected/desired behavior:**

No crash.
Building with the `--env dev` or indeed with no flags (e.g. `au build`) completes successfully.

` aurelia_project/environments/*.ts ` are identical and I have tried all combinations of the ` debug ` and ` testing ` properties.

* **What is the expected behavior?**
Project is built as it is with dev flag, except with production environment settings.

* **What is the motivation / use case for changing the behavior?**
Desired: No crash

**Comment by Ashthos** [comment]
Additional information:

I am targeting ` es6 ` in my ` tsconfig.json ` file, changing this to ` es5 ` does **not** solve the problem (as has been suggested in another issue)

**Comment by Ashthos** [comment]
Resolved:

in ` aurelia.json ` I had the following for aurelia-dialog:

```
          {
            "name": "aurelia-dialog",
            "path": "../node_modules/aurelia-dialog/dist/amd",
            "main": "aurelia-dialog",
            "env": "dev"
          },
```

Removing the ` "env": "dev" ` property allows the product to build successfully.

**Comment by EisenbergEffect** [comment]
Yes. You were in effect saying that you only wanted that dependency to be included in the dev build, but not production.
