### ISSUE TITLE
au process-css fails

### ISSUE THREAD

**Issue by omidh28** [aurelia/cli#432]
**I'm submitting a bug report**

* **Library Version:**
0.23.0

**Please tell us about your environment:**
* **Operating System:**
Linux (mint 17)

* **Node Version:**
7.2.1

* **NPM Version:**
4.0.2

* **Browser:**
all
* **Language:**
ESNext

**Current behavior:**
Running `au process-css` fails with this error: 

`Starting 'processCSS'...
{ uid: 0,
  name: 'processCSS',
  branch: false,
  error: 
   { TypeError: Cannot read property 'obj' of undefined
       at Object.exports.bundle (/home/omidh/Documents/Projects/testest/node_modules/aurelia-cli/lib/build/index.js:43:17)
       at processCSS (/home/omidh/Documents/Projects/testest/aurelia_project/tasks/process-css.js:9:17)
       at bound (domain.js:280:14)
       at runBound (domain.js:293:12)
       at asyncRunner (/home/omidh/Documents/Projects/testest/node_modules/async-done/index.js:36:18)
       at _combinedTickCallback (internal/process/next_tick.js:67:7)
       at process._tickDomainCallback (internal/process/next_tick.js:122:9)
     domain: 
      Domain {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        members: [] },
     domainThrown: true },
  duration: [ 0, 7526907 ],
  time: 1481211732659 }
{ TypeError: Cannot read property 'obj' of undefined
    at Object.exports.bundle (/home/omidh/Documents/Projects/testest/node_modules/aurelia-cli/lib/build/index.js:43:17)
    at processCSS (/home/omidh/Documents/Projects/testest/aurelia_project/tasks/process-css.js:9:17)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at asyncRunner (/home/omidh/Documents/Projects/testest/node_modules/async-done/index.js:36:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  domain: 
   Domain {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     members: [] },
  domainThrown: true }
`

**Expected/desired behavior:**

To reproduce this: 

1. run `au new test` with default options
2. run `cd test`
3. run `au process-css`

* **What is the expected behavior?**
Not giving error and doing its job :)

* **What is the motivation / use case for changing the behavior?**

**Comment by AStoker** [comment]
Sorry to dig this back up. What was the issue in the end?
