### ISSUE TITLE
Bundle construction looks for files in the wrong place

### ISSUE THREAD

**Issue by cavejay** [aurelia/cli#519]
**I'm submitting a bug report**

* **Library Version:**
0.24.0
0.26.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.2.0

* **NPM Version:**
3.10.9

* **Browser:**
Chrome 56.0

* **Language:**
ESNext

**Current behavior:**
Build fails to import local dependency of a 3rd party module. It attempts to import from the base directory rather than the local directory of the 3rd party module. 

What it tries and fails to import: `C:/Users/mzbal/proj/test/htmlparser2/lib/Parser.js`

What it should be importing: `C:/Users/mzbal/proj/test/node_modules/htmlparser2/lib/Parser.js`

It can be 'solved' by changing the require statement in the modules code from `require('./Parser.js')` to `require('./Parser')`. In this particular case it needs to be done to multiple requires through the htmlparser2 module's index.js to proceed with the build.

**Expected/desired behavior:**

To reproduce this bug:

1. Use the Aurelia CLI to create a new project with default settings and install its dependencies

2. Install Cheerio as a dependency: `npm install cheerio --save`

3. Add the following line to the top of the `src/app.js` file: `import * as cheerio from 'cheerio`

4. Add the following to the dependencies of your app-bundle in aurelia.json: 
```json
"dom-serializer",
          "domelementtype",
          {
            "name": "css-select",
            "path": "../node_modules/css-select",
            "main": "index"
          },
          {
            "name": "entities",
            "path": "../node_modules/entities",
            "main": "index"
          },
          {
            "name": "lodash.assign",
            "path": "../node_modules/lodash.assign",
            "main": "index.js"
          },
          {
            "name": "lodash.assignin",
            "path": "../node_modules/lodash.assignin",
            "main": "index.js"
          },
          {
            "name": "lodash.bind",
            "path": "../node_modules/lodash.bind",
            "main": "index.js"
          },
          {
            "name": "lodash.foreach",
            "path": "../node_modules/lodash.foreach",
            "main": "index.js"
          },
          {
            "name": "lodash.defaults",
            "path": "../node_modules/lodash.defaults",
            "main": "index.js"
          },
          {
            "name": "lodash.merge",
            "path": "../node_modules/lodash.merge",
            "main": "index.js"
          },
          {
            "name": "lodash.some",
            "path": "../node_modules/lodash.some",
            "main": "index.js"
          },
          {
            "name": "lodash.reject",
            "path": "../node_modules/lodash.reject",
            "main": "index.js"
          },
          {
            "name": "lodash.filter",
            "path": "../node_modules/lodash.filter",
            "main": "index.js"
          },
          {
            "name": "lodash.reduce",
            "path": "../node_modules/lodash.reduce",
            "main": "index.js"
          },
          {
            "name": "lodash.map",
            "path": "../node_modules/lodash.map",
            "main": "index.js"
          },
          {
            "name": "lodash.pick",
            "path": "../node_modules/lodash.pick",
            "main": "index.js"
          },
          {
            "name": "lodash.flatten",
            "path": "../node_modules/lodash.flatten",
            "main": "index.js"
          },
          {
            "name": "htmlparser2",
            "path": "../node_modules/htmlparser2",
            "main": "lib/index.js"
          },
          {
            "name": "cheerio",
            "path": "../node_modules/cheerio",
            "main": "lib/cheerio"
          },
```

5. run the build: `au build` or `au run`

You should be confronted by the following stack trace: 
```
C:\Users\mzbal\proj\test>au build
Starting 'readProjectConfiguration'...
Finished 'readProjectConfiguration'
Starting 'processMarkup'...
Starting 'processCSS'...
Starting 'configureEnvironment'...
Finished 'processCSS'
Finished 'processMarkup'
Finished 'configureEnvironment'
Starting 'buildJavaScript'...
Finished 'buildJavaScript'
Starting 'writeBundles'...
Tracing app...
{ uid: 8,
  name: 'writeBundles',
  branch: false,
  error:
   { Error: ENOENT: no such file or directory, open 'C:\Users\mzbal\proj\test\htmlparser2\lib\Parser.js'
       at Object.fs.openSync (fs.js:557:18)
       at Object.fs.readFileSync (fs.js:467:33)
       at Object.exports.readFileSync (C:\Users\mzbal\proj\test\node_modules\aurelia-cli\lib\file-system.js:49:13)
       at fileRead (C:\Users\mzbal\proj\test\node_modules\aurelia-cli\lib\build\bundled-source.js:83:31)
       at Object.context.fileRead (C:\Users\mzbal\proj\test\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:176:18)
       at Object.context.load (C:\Users\mzbal\proj\test\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:357:30)
       at Module.load (eval at <anonymous> (C:\Users\mzbal\proj\test\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:1), <anonymous>:832:29)
       at Module.fetch (eval at <anonymous> (C:\Users\mzbal\proj\test\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:1), <anonymous>:822:66)
       at Module.check (eval at <anonymous> (C:\Users\mzbal\proj\test\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:1), <anonymous>:854:30)
       at Module.enable (eval at <anonymous> (C:\Users\mzbal\proj\test\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:1), <anonymous>:1173:22)
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'C:\\Users\\mzbal\\proj\\test\\htmlparser2\\lib\\Parser.js',
     moduleTree: [ 'htmlparser2/lib/index' ],
     fileName: 'C:/Users/mzbal/proj/test/node_modules/htmlparser2/lib/index.js' },
  duration: [ 0, 308802102 ],
  time: 1488690540626 }
{ uid: 0,
  name: '<series>',
  branch: true,
  error:
   { Error: ENOENT: no such file or directory, open 'C:\Users\mzbal\proj\test\htmlparser2\lib\Parser.js'
       at Object.fs.openSync (fs.js:557:18)
       at Object.fs.readFileSync (fs.js:467:33)
       at Object.exports.readFileSync (C:\Users\mzbal\proj\test\node_modules\aurelia-cli\lib\file-system.js:49:13)
       at fileRead (C:\Users\mzbal\proj\test\node_modules\aurelia-cli\lib\build\bundled-source.js:83:31)
       at Object.context.fileRead (C:\Users\mzbal\proj\test\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:176:18)
       at Object.context.load (C:\Users\mzbal\proj\test\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:357:30)
       at Module.load (eval at <anonymous> (C:\Users\mzbal\proj\test\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:1), <anonymous>:832:29)
       at Module.fetch (eval at <anonymous> (C:\Users\mzbal\proj\test\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:1), <anonymous>:822:66)
       at Module.check (eval at <anonymous> (C:\Users\mzbal\proj\test\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:1), <anonymous>:854:30)
       at Module.enable (eval at <anonymous> (C:\Users\mzbal\proj\test\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:1), <anonymous>:1173:22)
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'C:\\Users\\mzbal\\proj\\test\\htmlparser2\\lib\\Parser.js',
     moduleTree: [ 'htmlparser2/lib/index' ],
     fileName: 'C:/Users/mzbal/proj/test/node_modules/htmlparser2/lib/index.js' },
  duration: [ 0, 541658204 ],
  time: 1488690540630 }
{ Error: ENOENT: no such file or directory, open 'C:\Users\mzbal\proj\test\htmlparser2\lib\Parser.js'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at Object.exports.readFileSync (C:\Users\mzbal\proj\test\node_modules\aurelia-cli\lib\file-system.js:49:13)
    at fileRead (C:\Users\mzbal\proj\test\node_modules\aurelia-cli\lib\build\bundled-source.js:83:31)
    at Object.context.fileRead (C:\Users\mzbal\proj\test\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:176:18)
    at Object.context.load (C:\Users\mzbal\proj\test\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:357:30)
    at Module.load (eval at <anonymous> (C:\Users\mzbal\proj\test\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:1), <anonymous>:832:29)
    at Module.fetch (eval at <anonymous> (C:\Users\mzbal\proj\test\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:1), <anonymous>:822:66)
    at Module.check (eval at <anonymous> (C:\Users\mzbal\proj\test\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:1), <anonymous>:854:30)
    at Module.enable (eval at <anonymous> (C:\Users\mzbal\proj\test\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:1), <anonymous>:1173:22)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\mzbal\\proj\\test\\htmlparser2\\lib\\Parser.js',
  moduleTree: [ 'htmlparser2/lib/index' ],
  fileName: 'C:/Users/mzbal/proj/test/node_modules/htmlparser2/lib/index.js' }
```

* **What is the expected behavior?**
Expected behaviour is that it should resolve the require statement as referencing the appropriate local file. 

* **What is the motivation / use case for changing the behavior?**
So that imports work properly.

**Comment by cavejay** [comment]
I'm not sure whether or not to make an additional ticket for the bug that happens after this problem is resolved. Using the method I mention in the ticket of removing the '.js' from the module's require statements I encounter another build error created by a different module using require to import a static json file. Rather than looking for the file itself, the bundler searches for a .json.js file and fails.

Should this be a new bug report?

**Comment by JeroenVinke** [comment]
@cavejay yes, please open another issue for that. Thanks!

**Comment by 3cp** [comment]
I believe this is now irrelevant to latest cli-bundler.
