### ISSUE TITLE
Unhandled rejection ReferenceError: _dec is not defined when running au build --env prod

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/cli#524]
**I'm submitting a bug report**
running `au build --env prod` results in `Unhandled rejection ReferenceError: _dec is not defined`. This repository has this issue: https://github.com/Thanood/md-todo. 

* **Library Version:**
0.26.1 (possibly lower versions as well)

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x|Linux (distro)|Windows [7|8|8.1|10]

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
all | TypeScript X.X | ESNext

cc @Thanood @danlofquist

**Comment by Jenselme** [comment]
I encountered the same problem yesterday. Downgrading uglify-js to 2.7.5 solved it.

**Comment by xiweicheng** [comment]
I met the same problem too.

**Comment by AStoker** [comment]
Do you have the trace of the console as it's running the build command? Might be a bit helpful

**Comment by Thanood** [comment]
@AStoker I've made a gist with the console output:
https://gist.github.com/Thanood/0ab6cd8ac03d1bc033ab3387e4f780f3

Also, here is the browser console stacktrace:

```
ReferenceError: _dec is not defined
    at Object.<anonymous> (http://localhost:9000/scripts/app-bundle.js:2:3659)
    at Object.execCb (http://localhost:9000/scripts/vendor-bundle.js:3:11016)
    at b.check (http://localhost:9000/scripts/vendor-bundle.js:3:4728)
    at b.enable (http://localhost:9000/scripts/vendor-bundle.js:3:7514)
    at b.init (http://localhost:9000/scripts/vendor-bundle.js:3:3872)
    at f (http://localhost:9000/scripts/vendor-bundle.js:3:2438)
    at Object.completeLoad (http://localhost:9000/scripts/vendor-bundle.js:3:10245)
    at HTMLScriptElement.onScriptLoad (http://localhost:9000/scripts/vendor-bundle.js:3:11171)
From previous event:
    at t.n.PLATFORM.global.System.n.PLATFORM.global.System.import.u.loadModule (http://localhost:9000/scripts/vendor-bundle.js:7:18065)
    at s (http://localhost:9000/scripts/vendor-bundle.js:6:15408)
    at http://localhost:9000/scripts/vendor-bundle.js:6:16065
From previous event:
    at l (http://localhost:9000/scripts/vendor-bundle.js:6:16041)
    at http://localhost:9000/scripts/vendor-bundle.js:6:15894
From previous event:
    at u (http://localhost:9000/scripts/vendor-bundle.js:6:15701)
    at Object.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:6:16313)
    at Object.execCb (http://localhost:9000/scripts/vendor-bundle.js:3:11016)
    at b.check (http://localhost:9000/scripts/vendor-bundle.js:3:4766)
    at b.enable (http://localhost:9000/scripts/vendor-bundle.js:3:7514)
    at Object.enable (http://localhost:9000/scripts/vendor-bundle.js:3:10073)
    at b.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:3:7371)
    at b.enable (http://localhost:9000/scripts/vendor-bundle.js:3:6871)
    at b.init (http://localhost:9000/scripts/vendor-bundle.js:3:3872)
    at http://localhost:9000/scripts/vendor-bundle.js:3:9389
```

Not sure if that helps at all.
It's around this part of `app-bundle.js`:
`e.OneTimeBindingBehavior=(_dec=(0,n.mixin)(a))(i=function(){this.mode=t.bindingMode.oneTime})`

**Comment by JeroenVinke** [comment]
@Thanood thanks for the info

So uglify-js@2.8.6 caused things to break:

2.7.5 - works OK
2.8.0 -  2.8.3, fails some sort of invalid left assign error
2.8.4 works OK
2.8.5 works OK
2.8.6 fails with `ReferenceError: _dec is not defined`
2.8.7 fails with `ReferenceError: _dec is not defined`

Failing:
`npm install uglify-js@2.8.7`
> e.OneTimeBindingBehavior=(_dec=(0,n.mixin)(a))(i=function(){this.mode=t.bindingMode.oneTime})||i,e.OneWayBindingBehavior=(_dec2=(0,n.mixin)

Working OK:
`npm install uglify-js@2.7.5`
> e.OneTimeBindingBehavior=(i=(0,n.mixin)(l),i(o=function(){this.mode=t.bindingMode.oneTime})||o),e.OneWayBindingBehavior=(r=(0,n.mixin)(l),

Deuglified failing app-bundle: https://gist.github.com/JeroenVinke/91f5bd222f8abbe0313095ce2cb22ea8

you'd think that [this](https://gist.github.com/JeroenVinke/91f5bd222f8abbe0313095ce2cb22ea8#file-gistfile1-txt-L1050-L1056) should be `__decorate` instead of `_dec`...

**Comment by JeroenVinke** [comment]
Opened a bug report [here](https://github.com/mishoo/UglifyJS2/issues/1580) and the maintainers quickly responded and suggested that the issue was already fixed in `master` (which has not yet been released). I was able to confirm this and since they release almost daily I assume this patch will be released very soon
