### ISSUE TITLE
Support minimatch in copyFiles

### ISSUE THREAD

**Issue by khuongduybui** [aurelia/cli#548]
**I'm submitting a feature request**

**Current behavior:**
I have to list every single file in copyFiles, e.g.
```
  "copyFiles": {
      "node_modules/mdi/css/materialdesignicons.min.css": "static_resources/vendor/mdi/css",
      "node_modules/mdi/fonts/materialdesignicons-webfont.eot": "static_resources/vendor/mdi/fonts",
      "node_modules/mdi/fonts/materialdesignicons-webfont.svg": "static_resources/vendor/mdi/fonts",
      "node_modules/mdi/fonts/materialdesignicons-webfont.ttf": "static_resources/vendor/mdi/fonts",
      "node_modules/mdi/fonts/materialdesignicons-webfont.woff": "static_resources/vendor/mdi/fonts",
      "node_modules/mdi/fonts/materialdesignicons-webfont.woff2": "static_resources/vendor/mdi/fonts"
  }
```

**Expected/desired behavior:**
I can specify a pattern matching files I want to copy, e.g.
```
  "copyFiles": {
      "node_modules/mdi/css/materialdesignicons.min.css": "static_resources/vendor/mdi/css",
      "node_modules/mdi/fonts/*": "static_resources/vendor/mdi/fonts"
  }
```

**What is the motivation / use case for changing the behavior?**
Most web font packages contain a few file types (eot, ttf, woff, woff2, svg).
On top of that, many web font packages contain variant (Bold, Italic, Light, Medium, Thick, Regular, etc.)
I currently have to import 25 files manually for NotoSans, for example: https://github.com/GreatWizard/notosans-fontface/tree/master/fonts

**Comment by fabioluz** [comment]
Your code works fine for me.

```
"copyFiles": {
      "node_modules/mdi/fonts/*": "static_resources/vendor/mdi/fonts"
  }
```

It copies everything inside the folder to `static_resources/vendor/mdi/fonts`.

**Comment by Vheissu** [comment]
@khuongduybui Wildcards should work fine. I'm doing something similar to what @fabioluz is doing and it works fine.

**Comment by khuongduybui** [comment]
I'm not sure if this is relevant but I'm using aurelia-cli 0.26.1 on Windows.
Putting a * into my copyFiles key gets me a bunch of errors that look similar to this:
```
{ Error: Invalid output folder
    at prepareWrite (C:\Users\duybui\code\builder\web\node_modules\vinyl-fs\lib\prepareWrite.js:37:11)
    at DestroyableTransform.saveFile [as _transform] (C:\Users\duybui\code\builder\web\node_modules\vinyl-fs\lib\dest\index.js:16:5)
    at DestroyableTransform.Transform._read (C:\Users\duybui\code\builder\web\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (C:\Users\duybui\code\builder\web\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (C:\Users\duybui\code\builder\web\node_modules\readable-stream\lib\_stream_writable.js:347:64)
    at writeOrBuffer (C:\Users\duybui\code\builder\web\node_modules\readable-stream\lib\_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (C:\Users\duybui\code\builder\web\node_modules\readable-stream\lib\_stream_writable.js:274:11)
    at DestroyableTransform.ondata (C:\Users\duybui\code\builder\web\node_modules\readable-stream\lib\_stream_readable.js:546:20)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:191:7)
  domain:
   Domain {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     members: [] },
  domainThrown: true }
```

**Comment by khuongduybui** [comment]
I think the problem is here: https://github.com/aurelia/cli/blob/master/lib/resources/tasks/copy-files.js#L19

```filePath``` here would be the ACTUAL file path (e.g. node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.eot), while ```files``` contain my wildcard (node_modules/bootstrap/dist/fonts/*), so ```key``` will end up being ```undefined```.

**Comment by khuongduybui** [comment]
I replaced that line with ```      const key = files.find(f => minimatch(filePath, f));``` and wildcards started to work like a charm.

**Comment by chabou-san** [comment]
The problem is not due to Windows, since I'm also having the issue for Aurelia-cli 0.26.1 on macOS. I tried on `bootstrap` library first since @fabioluz said it worked for him (and so is @Vheissu), but I got the same error than @khuongduybui. Using its proposed solution worked for me too.
