### ISSUE TITLE
Node module can't be loaded

### ISSUE THREAD

**Issue by djcaesar9114** [aurelia/cli#555]
**I'm submitting a bug report**

* **Library Version:**
0.24.0

**Please tell us about your environment:**
* **Operating System:**
Linux (Ubuntu 16.04)

* **Node Version:**
7.4.0

* **NPM Version:**
4.0.5

* **Browser:**
all

* **Language:**
TypeScript 2.1.6

**Current behavior:**
I'm adding a node_module as described here: http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/the-aurelia-cli/10
The module is "disconnect" (you can find it here: https://github.com/bartve/disconnect/)

I install it normally, typing `npm install disconnect --save` in the folder of my app.
I also edit `aurelia.json` correctly to insert in the `vendor-bundle.js` section :
```
          {
            "name": "disconnect",
            "path": "../node_modules/disconnect",
            "main": "index"
          },
```

When I buikd my app typing `au build`, but I get this error:

```
{ uid: 8,
  name: 'writeBundles',
  branch: false,
  error: 
   { Error: ENOENT: no such file or directory, open '/home/cesar/projets/aurelia/tracklist-manager/disconnect/lib/util.js'
       at Object.fs.openSync (fs.js:558:18)
       at Object.fs.readFileSync (fs.js:468:33)
       at Object.exports.readFileSync (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/file-system.js:49:13)
       at fileRead (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/bundled-source.js:83:31)
       at Object.context.fileRead (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:176:18)
       at Object.context.load (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:357:30)
       at Module.load (eval at <anonymous> (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:832:29)
       at Module.fetch (eval at <anonymous> (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:822:66)
       at Module.check (eval at <anonymous> (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:854:30)
       at Module.enable (eval at <anonymous> (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:1173:22)
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/home/cesar/projets/aurelia/tracklist-manager/disconnect/lib/util.js',
     moduleTree: [ 'disconnect/index' ],
     fileName: '/home/cesar/projets/aurelia/tracklist-manager/node_modules/disconnect/index.js' },
  duration: [ 4, 789092986 ],
  time: 1490043332523 }
{ uid: 0,
  name: '<series>',
  branch: true,
  error: 
   { Error: ENOENT: no such file or directory, open '/home/cesar/projets/aurelia/tracklist-manager/disconnect/lib/util.js'
       at Object.fs.openSync (fs.js:558:18)
       at Object.fs.readFileSync (fs.js:468:33)
       at Object.exports.readFileSync (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/file-system.js:49:13)
       at fileRead (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/bundled-source.js:83:31)
       at Object.context.fileRead (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:176:18)
       at Object.context.load (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:357:30)
       at Module.load (eval at <anonymous> (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:832:29)
       at Module.fetch (eval at <anonymous> (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:822:66)
       at Module.check (eval at <anonymous> (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:854:30)
       at Module.enable (eval at <anonymous> (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:1173:22)
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/home/cesar/projets/aurelia/tracklist-manager/disconnect/lib/util.js',
     moduleTree: [ 'disconnect/index' ],
     fileName: '/home/cesar/projets/aurelia/tracklist-manager/node_modules/disconnect/index.js' },
  duration: [ 8, 704096699 ],
  time: 1490043332559 }
{ Error: ENOENT: no such file or directory, open '/home/cesar/projets/aurelia/tracklist-manager/disconnect/lib/util.js'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.exports.readFileSync (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/file-system.js:49:13)
    at fileRead (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/bundled-source.js:83:31)
    at Object.context.fileRead (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:176:18)
    at Object.context.load (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:357:30)
    at Module.load (eval at <anonymous> (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:832:29)
    at Module.fetch (eval at <anonymous> (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:822:66)
    at Module.check (eval at <anonymous> (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:854:30)
    at Module.enable (eval at <anonymous> (/home/cesar/projets/aurelia/tracklist-manager/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:1173:22)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/cesar/projets/aurelia/tracklist-manager/disconnect/lib/util.js',
  moduleTree: [ 'disconnect/index' ],
  fileName: '/home/cesar/projets/aurelia/tracklist-manager/node_modules/disconnect/index.js' }
```

**Expected/desired behavior:**
I don't want this errors to occur, I want the module to be correctly loaded so that I can use it in a ValueConverter `using import disconnect from "disconnect"`.

**Comment by JeroenVinke** [comment]
Disconnect is not a browser lib so it should not be able to work in the browser.

**Comment by djcaesar9114** [comment]
OK, thanks for the info. I didn't know there was a difference. How can I distinguish packages meant for browsers from others? Thanks.

**Comment by JeroenVinke** [comment]
It usually is mentioned in the README of the library. But in this case, [url](https://github.com/bartve/disconnect/blob/master/lib/client.js#L5) is a nodejs thing. There are some more imports in there that would only work on nodejs

**Comment by djcaesar9114** [comment]
OK, thanks for everything, I now know that there are (at least) two kinds of packages!
