### ISSUE TITLE
Importing ES2015 module throw syntax error

### ISSUE THREAD

**Issue by RomainLanz** [aurelia/cli#556]
**I'm submitting a bug report**

* **Library Version:** 0.21.1 (aurelia-cli)
* **Operating System:** OSX 10.12.3
* **Node Version:** 7.4.0
* **NPM Version:** 4.0.5
* **Browser:** all
* **Language:** TypeScript 2.2.1

**Current behavior:**
I have installed a library that's coded using ES2015 syntax and when I'm requiring it inside the `aurelia_project/aurelia.json` `esprima` give me syntax error.

```
{ uid: 0,
  name: '<series>',
  branch: true,
  error:
   Error: Parse error using esprima for file: /Users/romainlanz/workspace/app.org/node_modules/myPackage/lib/index.js
   Error: Line 2: Unexpected token
  ....
}
```

Here's the content of the file (TypeScript compiled to ES2015):
```javascript
'use strict';
export * from './Auth';
export * from './Beach';
export * from './Requests';
export * from './Services';
export * from './Core';
//# sourceMappingURL=index.js.map
```

**What is the expected behavior?**
I expect Aurelia to require my package without throwing an error.

**Comment by RomainLanz** [comment]
Any news on this? @JeroenVinke

**Comment by JeroenVinke** [comment]
Not yet. Could you share a package that has this issue? 

@AStoker do you know if the bundler should support ES2015 modules?

**Comment by RomainLanz** [comment]
Thanks for your reply.

I haven't tested it but this repository should do the trick: https://github.com/RomainLanz/es2015-module

**Comment by AStoker** [comment]
@JeroenVinke, I think it should be fine, but what is most likely happening is it is failing on the compiling itself (the babel part). It could be that Babel is receiving the typescript file when it is expecting the module file? 
@RomainLanz, I would also try upgrading to the latest version of the CLI to see if that helps, or at least gives some better error logging.

**Comment by AStoker** [comment]
Also, not sure you need to use `'use strict'` when writing classes, since the compiler will do that for you (in fact, that might be part of the problem?...)

**Comment by RomainLanz** [comment]
So I have updated `aurelia-cli` to the latest version available (`0.27.0`) and I still have the same error.

I have created a simple application with the code I linked bellow and I have the same error.

```
{ uid: 0,
  name: '<series>',
  branch: true,
  error:
   Error: Parse error using esprima for file: /Users/romainlanz/workspace/test-au/node_modules/es2015-module/index.js
   Error: Line 3: Unexpected token
       at Object.context.load (/Users/romainlanz/workspace/test-au/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:392:21)
       at Module.load (eval at <anonymous> (/Users/romainlanz/workspace/test-au/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:832:29)
       at Module.fetch (eval at <anonymous> (/Users/romainlanz/workspace/test-au/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:822:66)
       at Module.check (eval at <anonymous> (/Users/romainlanz/workspace/test-au/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:854:30)
       at Module.enable (eval at <anonymous> (/Users/romainlanz/workspace/test-au/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:1173:22)
       at Object.enable (eval at <anonymous> (/Users/romainlanz/workspace/test-au/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:1554:39)
       at Object.context.enable (/Users/romainlanz/workspace/test-au/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:292:24)
       at Module.eval (eval at <anonymous> (/Users/romainlanz/workspace/test-au/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:1158:33)
       at eval (eval at <anonymous> (/Users/romainlanz/workspace/test-au/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:134:23)
       at each (eval at <anonymous> (/Users/romainlanz/workspace/test-au/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:59:31),
  duration: [ 1, 979110644 ],
  time: 1490630470145 }
```

**Comment by arabsight** [comment]
code outside the __src__ folder is not transpiled.

```js
// aurelia.json
"transpiler": {    
    //...
    "source": "src/**/*.js"
  }
```

**Comment by RomainLanz** [comment]
What do you think of adding a `format`/`moduleResolution`/`module` into the object syntax when defining dependencies?

It could be something like:

```
{
  "name": "es2015-module",
  "path": "../node_modules/es2015-module",
  "main": "index",
  "format": "es2015"
},
```

**Comment by JeroenVinke** [comment]
Seems like amodrotrace (which uses esprima) does not account for the `export * from x` syntax. Amodrotrace's [parse module](https://github.com/aurelia/cli/blob/master/lib/build/amodro-trace/lib/parse.js) calls esprima as:

> esprima.parse('export * from "./test";')

> Error: Line 1: Unexpected token
    at ErrorHandler.constructError (C:\Development\aurelia-app\node_modules\esprima\dist\esprima.js:3396:22)
    at ErrorHandler.createError (C:\Development\aurelia-app\node_modules\esprima\dist\esprima.js:3414:27)
    at Parser.unexpectedTokenError (C:\Development\aurelia-app\node_modules\esprima\dist\esprima.js:542:39)
    at Parser.tolerateUnexpectedToken (C:\Development\aurelia-app\node_modules\esprima\dist\esprima.js:555:42)
    at Parser.parseStatementListItem (C:\Development\aurelia-app\node_modules\esprima\dist\esprima.js:1795:31)
    at Parser.parseProgram (C:\Development\aurelia-app\node_modules\esprima\dist\esprima.js:3061:29)
    at Object.parse (C:\Development\aurelia-app\node_modules\esprima\dist\esprima.js:117:24)
    at repl:1:9
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:339:29)

When supplying `sourceType` esprima parses it correctly:
>  esprima.parse('export * from "./test";', { sourceType: 'module' })

> Program {
  type: 'Program',
  body: [ ExportAllDeclaration { type: 'ExportAllDeclaration', source: [Object] } ],
  sourceType: 'module' }

But even when supplying the `sourceType` in all usages of esprima in the parse.js module, the build succeeds but it did not any conversion to AMD:

![image](https://cloud.githubusercontent.com/assets/2189477/24394473/65d494ca-139c-11e7-85b8-bbc02a3b256d.png)

It could be the case that the parse module only looks for named declarations, whereas esprima returns `ExportAllDeclarations` for the `export * from x` syntax:

![image](https://cloud.githubusercontent.com/assets/2189477/24394511/86047620-139c-11e7-93ba-cb59eba099c8.png)

**Comment by JeroenVinke** [comment]
`import {something} from './test'` doesn't seem to be recognized by Amodrotrace either, making me think that amodrotrace does not support ES2015 at all.

**Comment by JeroenVinke** [comment]
@RomainLanz unfortunately, from what i've seen we would have to do some work to amodrotrace (possibly together in collaboration with the folks from amodrotrace) in order to get this working. So I expect it will take some time to resolve. I suggest to look for alternatives. Perhaps you can fork the library and transpile it, then use the fork in the app, or use a different library that does use AMD/commonjs.

**Comment by RomainLanz** [comment]
Yup. Since it's my library I have configured my compiling task to output CommonJS as default, ES2015 module resolution for TreeShaking and UMD for browser standalone script.

I'll try tomorrow to add it to Aurelia, it should take by default the CommonJS version.

**Comment by DrSammyD** [comment]
FYI this is an issue i'm running into with the new bootstrap 4 package 
![image](https://cloud.githubusercontent.com/assets/774363/26039614/d598e7d4-38d1-11e7-98ad-2989fc4fd34f.png)

**Comment by DrSammyD** [comment]
Looks like Amodrotrace just updated their esprima dependency! https://github.com/amodrojs/amodro-trace/releases/tag/1.0.0

**Comment by jwx** [comment]
@RomainLanz Is this issue resolved in version 0.30 of the CLI?

**Comment by Alexander-Taran** [comment]
```
async triageQuestion(id) =>{
 let response = await confirmResolved( { timeout : longTime } )
 if(!response) {
    closeQuestion(id,randomReason())
 }
}
```

**Comment by Stickiler** [comment]
With a brand new project, Typescript, RequireJS, Aurelia-Cli bundler setup, importing the `ol` npm package, causes this error to occur.
This is the only thing added to aurelia.json from a basic cli setup.
`{
            "name": "ol",
            "path": "../node_modules/ol",
            "main": "index"
          },`

**Comment by avrahamcool** [comment]
@EisenbergEffect looks like this should work with the new tracer - and can be closed.

**Comment by huochunpeng** [comment]
Yes, new tracer supports esm module format.
