### ISSUE TITLE
bundling locally defined module

### ISSUE THREAD

**Issue by simonfox** [aurelia/cli#590]
* **Library Version:**
0.27.0

* **Operating System:**
Windows 10

* **Node Version:**
6.2.1

* **NPM Version:**
4.5

* **Language:**
all 

I'm trying to add `npm:uuid@3.0.1` to my project. This package is a node package, but provides an optional browser implementation. I've seen the approach described in https://github.com/aurelia/animator-velocity/issues/13 and am trying to follow that to attempt to create a local module that uses the browser implementation of `uuid`.

Problem is the bundler doesn't seem to like the dependency path in `aurelia.json`:
```
{
  "name": "uuid-shim",
  "path": "../scripts/uuid-shim"
}
```

I get the following exception: 
```
{ uid: 9,
  name: 'writeBundles',
  branch: false,
  error:
   TypeError: Path must be a string. Received undefined
       at assertPath (path.js:7:11)
       at Object.normalize (path.js:1179:5)
       at includes.filter.map.inclusion (D:\code\radio\src\sales\Drive.Sales.UI\node_modules\aurelia-cli\lib\build\bundle.js:95:45)
       at Array.map (native)
       at getDependencyLocations (D:\code\radio\src\sales\Drive.Sales.UI\node_modules\aurelia-cli\lib\build\bundle.js:94:8)
       at bundles.reduce (D:\code\radio\src\sales\Drive.Sales.UI\node_modules\aurelia-cli\lib\build\bundler.js:204:53)
       at Array.reduce (native)
       at getAllDependencyLocations (D:\code\radio\src\sales\Drive.Sales.UI\node_modules\aurelia-cli\lib\build\bundler.js:204:25)
       at getInclusion (D:\code\radio\src\sales\Drive.Sales.UI\node_modules\aurelia-cli\lib\build\bundled-source.js:157:44)
       at amodroTrace.then.traceResult (D:\code\radio\src\sales\Drive.Sales.UI\node_modules\aurelia-cli\lib\build\bundled-source.js:147:19),
  duration: [ 6, 53697754 ],
  time: 1491370564805 }
{ uid: 0,
  name: '<series>',
  branch: true,
  error:
   TypeError: Path must be a string. Received undefined
       at assertPath (path.js:7:11)
       at Object.normalize (path.js:1179:5)
       at includes.filter.map.inclusion (D:\code\radio\src\sales\Drive.Sales.UI\node_modules\aurelia-cli\lib\build\bundle.js:95:45)
       at Array.map (native)
       at getDependencyLocations (D:\code\radio\src\sales\Drive.Sales.UI\node_modules\aurelia-cli\lib\build\bundle.js:94:8)
       at bundles.reduce (D:\code\radio\src\sales\Drive.Sales.UI\node_modules\aurelia-cli\lib\build\bundler.js:204:53)
       at Array.reduce (native)
       at getAllDependencyLocations (D:\code\radio\src\sales\Drive.Sales.UI\node_modules\aurelia-cli\lib\build\bundler.js:204:25)
       at getInclusion (D:\code\radio\src\sales\Drive.Sales.UI\node_modules\aurelia-cli\lib\build\bundled-source.js:157:44)
       at amodroTrace.then.traceResult (D:\code\radio\src\sales\Drive.Sales.UI\node_modules\aurelia-cli\lib\build\bundled-source.js:147:19),
  duration: [ 22, 761216000 ],
  time: 1491370564821 }
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.normalize (path.js:1179:5)
    at includes.filter.map.inclusion (D:\code\radio\src\sales\Drive.Sales.UI\node_modules\aurelia-cli\lib\build\bundle.js:95:45)
    at Array.map (native)
    at getDependencyLocations (D:\code\radio\src\sales\Drive.Sales.UI\node_modules\aurelia-cli\lib\build\bundle.js:94:8)
    at bundles.reduce (D:\code\radio\src\sales\Drive.Sales.UI\node_modules\aurelia-cli\lib\build\bundler.js:204:53)
    at Array.reduce (native)
    at getAllDependencyLocations (D:\code\radio\src\sales\Drive.Sales.UI\node_modules\aurelia-cli\lib\build\bundler.js:204:25)
    at getInclusion (D:\code\radio\src\sales\Drive.Sales.UI\node_modules\aurelia-cli\lib\build\bundled-source.js:157:44)
    at amodroTrace.then.traceResult (D:\code\radio\src\sales\Drive.Sales.UI\node_modules\aurelia-cli\lib\build\bundled-source.js:147:19)
```
Where am I going wrong here?

**Comment by JeroenVinke** [comment]
That is because the CLI does not support bundling files outside of of the node modules folder yet. https://github.com/aurelia/cli/issues/567 is similar. A PR that adds this support has been made
