### ISSUE TITLE
Error: Options {"loose":true} passed to babel-preset-es2015/lib/index.js

### ISSUE THREAD

**Issue by agsci2017** [aurelia/cli#605]
**I'm submitting a bug report**

* **Library Version:**
aurelia-cli 0.27.0

**Please tell us about your environment:**
* **Operating System:**
Fedora Workstation 25

* **Node Version:**
6.10.0

* **NPM Version:**
3.10.10

* **Browser:**
all

* **Language:**
ESNext

**Steps:**
Create project with "au new" using default settings(ESNext by default, with project dependencies installation).
Run project with "au run".

**Current behavior:**
/home/user/aurelia_project1/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^
Error: Options {"loose":true} passed to /home/user/aurelia_project1/node_modules/babel-preset-es2015/lib/index.js which does not accept options. (While processing preset: "/home/user/aurelia_project1/node_modules/babel-preset-es2015/lib/index.js") (While processing preset: "/home/user/aurelia_project1/node_modules/babel-preset-es2015/lib/index.js")
    at /home/user/aurelia_project1/node_modules/babel-core/lib/transformation/file/options/option-manager.js:314:17
    at Array.map (native)
    at OptionManager.resolvePresets (/home/user/aurelia_project1/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/user/aurelia_project1/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/user/aurelia_project1/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/user/aurelia_project1/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/home/user/aurelia_project1/node_modules/babel-register/lib/node.js:103:45)
    at loader (/home/user/aurelia_project1/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/home/user/aurelia_project1/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)

**Expected/desired behavior:**

Succesfull run on server(http://localhost:9000)

**Remark:**
if "au new" set to Typescript usage, everything is ok(server runs, i see "Hello world" message in a browser).
It seems that problem specifically with babel transpiler.

**Comment by agsci2017** [comment]
Localized the problem.
If you create a project using "au new" with long name("aurelia_project1") and then run "au run" you'll get an error("option {loose:true} passed to babel").
If you create a project using "au new" with simple name("aurelia") and then run "au run", tracing, building and server runs without any errors.

**Comment by agsci2017** [comment]
aurelia_project1 (err)
aurelia_project2 (err)
aurelia_projecty (err)
aurelia_project (err)
aurelia_projec (ok)
aurelia_proje (ok)
aurelia_proj (ok)
aurelia_projectrge6djghsdjhg3r3 (err)
aurelia_projdir (ok)
aurelia_projection_of_light (err)

It seems that name conflict with internal directory "aurelia_project" happens.
Project name that starts with `aurelia_project` causes an error.

**Comment by JeroenVinke** [comment]
Thank you for investigating!
