### ISSUE TITLE
Cannot find module 'object.defaults' on build

### ISSUE THREAD

**Issue by gama410** [aurelia/cli#653]
**I'm submitting a bug report**

* **Library Version:**
0.27.0

**Please tell us about your environment:**
* **Operating System:**
windows 10

* **Node Version:**
7.7.4

* **NPM Version:**
5.0.3

* **Browser:**
all (irrelevant)
* **Language:**
TypeScript 2.1.5

**Current behavior:**
When running the command 'au build' (or 'au run'), the compilation fails with the following error:
` Error: Cannot find module 'object.defaults'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\GMA\Documents\Sources\FluFS2\FluFS\Development\Code\UI\FluFS.Web.View\node_modules\gulp\node_modules\glob-watcher\index.js:6:1
6)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND'`

When I install the mentioned package by doing 
`npm install object.defaults`
it works without issue. I noticed there is no dependency for this package in aurelia-cli's package.json so maybe it's a simple ommission...

**Expected/desired behavior:**

the compilation should work

* **What is the expected behavior?**
the compilation should work

* **What is the motivation / use case for changing the behavior?**
the compilation should work

**Comment by JeroenVinke** [comment]
I'm suspecting that something went wrong during `npm install`, because the error occurs in `glob-watcher` which lists `object.defaults` as a [dependency](https://github.com/gulpjs/glob-watcher/blob/master/package.json#L27)

**Comment by gama410** [comment]
Thanks Jeroen, you're right : I should have looked a little longer at the stack trace. I got a little carried away by the newsletter about the update to aurelia-cli...
