### ISSUE TITLE
JSPM Section strategy - Path must be a string

### ISSUE THREAD

**Issue by diegohb** [aurelia/cli#684]
**I'm submitting a bug report**

* **Library Version:**
aurelia-cli v0.30.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Language:**
all

**Current behavior:**

> PS E:\dev\projects\playground\au-leaflet-cluster> au import systemjs-debugger
> INFO [Importer] ---------------------------------------------------------
> INFO [Importer] *********** Configuring systemjs-debugger ***********
> INFO [Importer] [OK] Going to execute the "JSPM Section Strategy" strategy
> TypeError: Path must be a string. Received undefined
>     at assertPath (path.js:7:11)
>     at Object.join (path.js:1211:7)
>     at JSPMSectionStrategy.execute (E:\dev\projects\playground\au-leaflet-cluster\node_modules\aurelia-cli\lib\importer\strategies\jspm-section.js:33:36)
>     at findStrategy.then.strategy (E:\dev\projects\playground\au-leaflet-cluster\node_modules\aurelia-cli\lib\importer\package-importer.js:39:39)
> PS E:\dev\projects\playground\au-leaflet-cluster>

**Expected/desired behavior:**
it should install...

**Comment by diegohb** [comment]
a related question ... is the "map" and "meta" properties of the systemJS configuration purposely hidden/disallowed in the aurelia.json config . ?

**Comment by JeroenVinke** [comment]
we need to confirm that it will work as expected if we expose that. The CLI bundler uses requirejs internally, which is less powerful than systemjs' version of `map` so there may be some issues there. If that is the case we'll need to figure out what is the best way to move forward.
