### ISSUE TITLE
Cannot find module async

### ISSUE THREAD

**Issue by robgallen** [aurelia/cli#696]
**I'm submitting a bug report**

* **Library Version:**
0.30.1

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
6.9.1

* **NPM Version:**
5.0.3

* **Browser:**
all

* **Language:**
all

**Current behavior:**
module.js:471
    throw err;
    ^

Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\********\AppData\Roaming\npm\node_modules\aurelia-cli\node_modules\npm\node_modules\request\node_modules\form-data\lib\form_d
ata.js:9:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Expected/desired behavior:**
Repro steps: Open command line, run `au new`, accepting all default values.

* **What is the expected behavior?**
Project should be created with no errors and `au run` should run the project.

**Comment by JeroenVinke** [comment]
I haven't seen this one before. I think it may be an NPM/Node.js issue. Could you try:

1. npm uninstall aurelia-cli -g
2. npm cache clear
3. npm install aurelia-cli -g

if it still doesn't work, maybe update Node.js and try the above again. Let me know how it goes
