### ISSUE TITLE
Unable to create an ASP.NET Core project template

### ISSUE THREAD

**Issue by Lani** [aurelia/cli#734]
**I'm submitting a bug report**

* **Library Version:**
0.31.3

**Please tell us about your environment:**
* **Operating System:**
Linux (Ubuntu 17.04)

* **Node Version:**
8.1.2

* **NPM Version:**
5.3.0

* **Browser:**
n/a

* **Language:**
ESNext

**Current behavior:**
The aurelia cli gives the following error when creating a new custom ASP.NET Core project: `Error locating resource: content/javascriptservices/Project.csproj`

**Expected/desired behavior:**

1. Run `au new au-asp`
2. Enter the following options:
```
    Name: au-asp
    Platform: ASP.NET Core
    Bundler: Webpack
    Loader: None
    Transpiler: Babel
    Markup Processor: Maximum Minification
    CSS Processor: Sass
    Unit Test Runner: Jest
    Integration Test Runner: Protractor
    Editor: Visual Studio Code
```

* **What is the expected behavior?**
The CLI should generate a new ASP.NET Core project template.

* **What is the motivation / use case for changing the behavior?**
To be able to create an ASP.NET Core project template. 

* **Full error output**
```
Project Configuration

    Name: au-asp
    Platform: ASP.NET Core
    Bundler: Webpack
    Loader: None
    Transpiler: Babel
    Markup Processor: Maximum Minification
    CSS Processor: Sass
    Unit Test Runner: Jest
    Integration Test Runner: Protractor
    Editor: Visual Studio Code


Would you like to create this project?

1. Yes (Default)
   Creates the project structure based on your selections.
2. Restart
   Restarts the wizard, allowing you to make different selections.
3. Abort
   Aborts the new project wizard.

[Yes]> 
Error locating resource: content/javascriptservices/Project.csproj
{ Error: Cannot find module './content/javascriptservices/Project.csproj'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.resolve (internal/module.js:18:19)
    at exports.locateResource (/home/lani/.nvm/versions/node/v8.1.2/lib/node_modules/aurelia-cli/lib/resources/index.js:5:20)
    at Function.resource (/home/lani/.nvm/versions/node/v8.1.2/lib/node_modules/aurelia-cli/lib/project-item.js:223:45)
    at exports.ProjectTemplate.configureJavascriptServices (/home/lani/.nvm/versions/node/v8.1.2/lib/node_modules/aurelia-cli/lib/commands/new/project-template.js:124:19)
    at module.exports (/home/lani/.nvm/versions/node/v8.1.2/lib/node_modules/aurelia-cli/lib/commands/new/buildsystems/webpack/platforms/aspnetcore.js:8:4)
    at module.exports (/home/lani/.nvm/versions/node/v8.1.2/lib/node_modules/aurelia-cli/lib/commands/new/buildsystems/webpack/platforms/index.js:13:3)
    at module.exports (/home/lani/.nvm/versions/node/v8.1.2/lib/node_modules/aurelia-cli/lib/commands/new/buildsystems/webpack/index.js:9:3)
    at ui.clearScreen.then.then.then.answer (/home/lani/.nvm/versions/node/v8.1.2/lib/node_modules/aurelia-cli/lib/workflow/activities/project-create.js:48:11)
    at <anonymous> code: 'MODULE_NOT_FOUND' }
ERROR [ProjectCreation] Failed to create the project due to an error: Cannot find module './content/javascriptservices/Project.csproj'
INFO [ProjectCreation] Error: Cannot find module './content/javascriptservices/Project.csproj'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.resolve (internal/module.js:18:19)
    at exports.locateResource (/home/lani/.nvm/versions/node/v8.1.2/lib/node_modules/aurelia-cli/lib/resources/index.js:5:20)
    at Function.resource (/home/lani/.nvm/versions/node/v8.1.2/lib/node_modules/aurelia-cli/lib/project-item.js:223:45)
    at exports.ProjectTemplate.configureJavascriptServices (/home/lani/.nvm/versions/node/v8.1.2/lib/node_modules/aurelia-cli/lib/commands/new/project-template.js:124:19)
    at module.exports (/home/lani/.nvm/versions/node/v8.1.2/lib/node_modules/aurelia-cli/lib/commands/new/buildsystems/webpack/platforms/aspnetcore.js:8:4)
    at module.exports (/home/lani/.nvm/versions/node/v8.1.2/lib/node_modules/aurelia-cli/lib/commands/new/buildsystems/webpack/platforms/index.js:13:3)
    at module.exports (/home/lani/.nvm/versions/node/v8.1.2/lib/node_modules/aurelia-cli/lib/commands/new/buildsystems/webpack/index.js:9:3)
    at ui.clearScreen.then.then.then.answer (/home/lani/.nvm/versions/node/v8.1.2/lib/node_modules/aurelia-cli/lib/workflow/activities/project-create.js:48:11)
    at <anonymous>
```

**Comment by JeroenVinke** [comment]
This must be because of the capital letter `P` combined with Linux, since this works fine on Windows. 

Could you confirm by opening up `/home/lani/.nvm/versions/node/v8.1.2/lib/node_modules/aurelia-cli/lib/commands/new/project-template.js` and replacing that capital letter P on line 124 to a lowercase?

**Comment by Lani** [comment]
Confirmed! That solves it! Thanks for the quick reply. 

(I get another error now, but I think that is because I do not have the dotnet runtime installed, will open another issue in case it is something else).
