### ISSUE TITLE
Au install fails on new webpack procject

### ISSUE THREAD

**Issue by alexandru-calinoiu** [aurelia/cli#735]
**I'm submitting a bug report**

* **Library Version:**
0.31.3

**Please tell us about your environment:**
* **Operating System:**
Linux OpenSuse Tumbleweed

* **Node Version:**
6.11.1

* **NPM Version:**
3.10.10

* **Browser:**
none

* **Language:**
TypeScript 2.4

**Current behavior:**
Runing `au install` fails with:

```
INFO [Install] The packages were successfully installed. Going to import them now.
TypeError: Cannot read property 'length' of undefined
    at getDefaultBundle (/home/calin/Playground/aurelia-apollo-webpack/node_modules/aurelia-cli/lib/project.js:162:16)
    at getContainer (/home/calin/Playground/aurelia-apollo-webpack/node_modules/aurelia-cli/lib/importer/import-engine.js:55:76)
    at importPackage (/home/calin/Playground/aurelia-apollo-webpack/node_modules/aurelia-cli/lib/importer/import-engine.js:42:26)
    at _importPackage (/home/calin/Playground/aurelia-apollo-webpack/node_modules/aurelia-cli/lib/importer/import-engine.js:34:19)
    at import (/home/calin/Playground/aurelia-apollo-webpack/node_modules/aurelia-cli/lib/importer/import-engine.js:38:12)
    at execute (/home/calin/Playground/aurelia-apollo-webpack/node_modules/aurelia-cli/lib/commands/import/command.js:23:14)
    at packageInstaller.install.then.then (/home/calin/Playground/aurelia-apollo-webpack/node_modules/aurelia-cli/lib/commands/install/command.js:28:38)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Expected/desired behavior:**
Should not fail, my guess is that it should only install the package for webpack based templates

**Comment by JeroenVinke** [comment]
Thanks for opening the bug report. `au install` is specifically for the Aurelia CLI bundler, and not the Webpack bundler. We'll have to disable that
