### ISSUE TITLE
Use of symlinks in src does not work

### ISSUE THREAD

**Issue by Jule-** [aurelia/cli#772]
**I'm submitting a bug report**

* **Library Version:**
0.31.3

**Please tell us about your environment:**
* **Operating System:**
OSX 10.13|Windows 10

* **Node Version:**
6.9.2

* **NPM Version:**
3.10.9

* **Browser:**
all

* **Language:**
ESNext

* **Loader/bundler:**
RequireJS

**Current behavior:**
Following this kind of project hierarchy:
```
rootFolder
├── projectA
│   ├── aurelia_project
│   ├── src
│   │   ├── main.js
│   │   ├── shared_sources -> ../../shared_sources
├── projectB
│   ├── aurelia_project
│   ├── src
│   │   ├── main.js
│   │   ├── shared_sources -> ../../shared_sources
├── shared_sources
│   ├── class.js
```
And assuming that each `main.js` have an `import Class from './shared_sources/class';`, when I try to build with `au build` I have some errors due to symlinks. If I past `class.js` in a standard folder all goes fine.

Error:
```
commonJs.convert: COULD NOT CONVERT: C:/rootFolder/projectA/src/shared_sources/class.js, so skipping it. Error was: Error: Line 1: Unexpected token
Error occurred while tracing
{ Error: Parse error using esprima for file: C:/rootFolder/projectA/src/shared_sources/class.js
Error: Line 1: Unexpected token
    at Object.context.load (C:\rootFolder\projectA\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:392:21)
    at Object.load (eval at <anonymous> (C:\rootFolder\projectA\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:832:29)
    at Object.fetch (eval at <anonymous> (C:\rootFolder\projectA\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:822:66)
    at Object.check (eval at <anonymous> (C:\rootFolder\projectA\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:854:30)
    at Object.enable (eval at <anonymous> (C:\rootFolder\projectA\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:1173:22)
    at Object.enable (eval at <anonymous> (C:\rootFolder\projectA\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:1554:39)
    at Object.context.enable (C:\rootFolder\projectA\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:292:24)
    at Object.eval (eval at <anonymous> (C:\rootFolder\projectA\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:1158:33)
    at eval (eval at <anonymous> (C:\rootFolder\projectA\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:134:23)
    at each (eval at <anonymous> (C:\rootFolder\projectA\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:59:31)
  moduleTree: [ 'main' ],
  fileName: 'C:/rootFolder/projectA/src/main.js' }
```

* **What is the expected behavior?**
I expect that aurelia-cli build system can follow symlinks correctly.

* **What is the motivation / use case for changing the behavior?**
Sometimes you want to share some source code between two aurelia project because they use the same models for example and you don't want to make a new repository for that. And you don't want to add in your developpement process to change your library, commit, push, then npm/yarn again in each of your subprojects in order to test your changes.

**Comment by Alexander-Taran** [comment]
@3cp is this still relevant?

**Comment by 3cp** [comment]
This works on latest skeleton. It's probably some default change between gulp v3 and v4.

If having trouble with symlink with latest skeleton, try gulp.src's options `follow: true`.
https://gulpjs.com/docs/en/api/src#options

**Comment by 3cp** [comment]
The gulp.src option can be edited in various files in `aurelia_project/tasks/` whenever gulp.src is used.

**Comment by 3cp** [comment]
Oh, it works on macOS where symlink is true symlink.
No sure about windows, I guess symlink is simulated on the platform which causes many trouble. (My knowledge might be wrongly based outdated file system in windows)

**Comment by Alexander-Taran** [comment]
@3cp thank you
