### ISSUE TITLE
DEV_ENV issues requiring local module from Aureliafile

### ISSUE THREAD

**Issue by joelcoxokc** [aurelia/cli#79]
In development we are using ES6. However, when I try to require the configFile, it is requiring(`aurelia-cli`);

This causes it to enforce a local require. 

Once the file tries requiring I get this message:

```shell
(function (exports, require, module, __filename, __dirname) { import {Program}
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Module._compile (module.js:439:25)
    at Module._extensions..js (module.js:474:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/joelcox1/Jobs/Aurelia/cli/aurelia-cli/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:161:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/joelcox1/Jobs/Aurelia/cli/cli-test-2/node_modules/aurelia-cli/index.js:7:11)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
```

@ahmedshuhel Any thoughts?

**Comment by ahmedshuhel** [comment]
@joelcoxokc Could you please explain this a little bit more. How do I reproduce this issue?

**Comment by joelcoxokc** [comment]
@ahmedshuhel When I run aurelia init. It will generate an Aureliafile, and intall aurelia-cli if not already installed. 

This is probably not an issue in production. However, the second we try and run any command, while a local installation exists... I get the above Error. 

in your cli directory run `pwd`

Copy the result and in a generated project directory run 

```
npm install --save <pwd result>
```
