### ISSUE TITLE
au new errors

### ISSUE THREAD

**Issue by johnmanko** [aurelia/cli#799]
**I'm submitting a bug report**

* **Library Version:**
```
$ au -v
0.32.0
```

**Please tell us about your environment:**
* **Operating System:**
Ubuntu Linux 17.10 x86_64 (kernel 4.13.0-19-generic)

* **Node Version:**
```
$ node -v
v9.3.0
```

* **NPM Version:**
```
$ npm -v
5.6.0
```

* **Browser:**
Not relevant.

* **Language:**
TypeScript 

* **Loader/bundler:**
Not relevant.

**Current behavior:**
`au new test`

```
                      _ _          ____ _     ___
  __ _ _   _ _ __ ___| (_) __ _   / ___| |   |_ _|
 / _` | | | | '__/ _ \ | |/ _` | | |   | |    | |
| (_| | |_| | | |  __/ | | (_| | | |___| |___ | |
 \__,_|\__,_|_|  \___|_|_|\__,_|  \____|_____|___|


Would you like to use the default setup or customize your choices?

1. Default ESNext (Default)
   A basic web-oriented setup with Babel and RequireJS for modern JavaScript development.
2. Default TypeScript
   A basic web-oriented setup with TypeScript and RequireJS for modern JavaScript development.
3. Custom
   Select loaders (requirejs/systemjs), bundlers (cli/webpack), transpilers, CSS pre-processors and more.

[Default ESNext]> 2
```
```
Project Configuration

    Name: test
    Platform: Web
    Bundler: Aurelia-CLI
    Loader: RequireJS
    Transpiler: TypeScript
    Markup Processor: Minimal Minification
    CSS Processor: None
    Unit Test Runner: Karma
    Editor: Visual Studio Code


Would you like to create this project?

1. Yes (Default)
   Creates the project structure based on your selections.
2. Restart
   Restarts the wizard, allowing you to make different selections.
3. Abort
   Aborts the new project wizard.

[Yes]> 1
```
```
Project structure created and configured.


Would you like to install the project dependencies?

1. Yes (Default)
   Installs all server, client and tooling dependencies needed to build the project.
2. No
   Completes the new project wizard without installing dependencies.

[Yes]> 1
```
```
Installing project dependencies.
npm ERR! git checkout 71c094a51c7972d26f557899ddecab0210ef3776: error: Your local changes to the following files would be overwritten by checkout:
npm ERR! git checkout 71c094a51c7972d26f557899ddecab0210ef3776: 	docs/why-use-pump/pipe-error.png
npm ERR! git checkout 71c094a51c7972d26f557899ddecab0210ef3776: 	docs/why-use-pump/pump-error.png
npm ERR! git checkout 71c094a51c7972d26f557899ddecab0210ef3776: Please commit your changes or stash them before you switch branches.
npm ERR! git checkout 71c094a51c7972d26f557899ddecab0210ef3776: Aborting
npm ERR! git checkout 71c094a51c7972d26f557899ddecab0210ef3776: 
npm ERR! git checkout 71c094a51c7972d26f557899ddecab0210ef3776: error: Your local changes to the following files would be overwritten by checkout:
npm ERR! git checkout 71c094a51c7972d26f557899ddecab0210ef3776: 	docs/why-use-pump/pipe-error.png
npm ERR! git checkout 71c094a51c7972d26f557899ddecab0210ef3776: 	docs/why-use-pump/pump-error.png
npm ERR! git checkout 71c094a51c7972d26f557899ddecab0210ef3776: Please commit your changes or stash them before you switch branches.
npm ERR! git checkout 71c094a51c7972d26f557899ddecab0210ef3776: Aborting
npm ERR! git checkout 71c094a51c7972d26f557899ddecab0210ef3776: 
npm ERR! git checkout 71c094a51c7972d26f557899ddecab0210ef3776: error: Your local changes to the following files would be overwritten by checkout:
npm ERR! git checkout 71c094a51c7972d26f557899ddecab0210ef3776: 	docs/why-use-pump/pipe-error.png
npm ERR! git checkout 71c094a51c7972d26f557899ddecab0210ef3776: 	docs/why-use-pump/pump-error.png
npm ERR! git checkout 71c094a51c7972d26f557899ddecab0210ef3776: Please commit your changes or stash them before you switch branches.
npm ERR! git checkout 71c094a51c7972d26f557899ddecab0210ef3776: Aborting
npm ERR! git checkout 71c094a51c7972d26f557899ddecab0210ef3776: 
Uncaught promise rejection:
{ Error: Command failed: git checkout 71c094a51c7972d26f557899ddecab0210ef3776
error: Your local changes to the following files would be overwritten by checkout:
	docs/why-use-pump/pipe-error.png
	docs/why-use-pump/pump-error.png
Please commit your changes or stash them before you switch branches.
Aborting

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'git checkout 71c094a51c7972d26f557899ddecab0210ef3776',
  parent: 'test' }

```

* **What is the expected behavior?**
Newly created project without errors.

**Comment by andrewwiik** [comment]
I could not reproduce this issue on my Windows 10 Machine with the same node and npm version and project creation options

**Comment by johnmanko** [comment]
@andrewwiik Thanks, Andy. I'll dig deeper to resolve this.  @EisenbergEffect, I guess if more users don't report an issue then this can be closed. Closing now.
