### ISSUE TITLE
application created with aurelia CLI fails to run

### ISSUE THREAD

**Issue by adriatic** [aurelia/cli#863]
**I'm submitting a bug report**

* **Library Version:**
major.minor.patch-pre
0.33.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x|Linux (distro)|Windows [7|8|8.1|10]

* **Node Version:**
6.2.0

8.8.4

* **NPM Version:**
3.8.9

5.8.0

* **Browser:**
Chrome Version 65.0.3325.181 (Official Build) (64-bit)
* **Language:**
Typescript
2.5
* **Loader/bundler:**
 webpack 4.4.1

**Current behavior:**
Minial typescript application built to use webpack fails to run
* **What is the expected behavior?**

This is my app configuration:
```
Project Configuration

    Name: aurelia-app
    Platform: Web
    Bundler: Webpack
    Loader: None
    Transpiler: TypeScript
    Markup Processor: Minimal Minification
    CSS Processor: None
    Unit Test Runner: Jest
    Unit Test Runner: Karma
    Integration Test Runner: None
    Editor: Visual Studio Code
```
- When asked `Would you like to create this project?`, I answered `Yes`
- When asked `Would you like to install the project dependencies?` I answered `Yes

```
Installing project dependencies.
yarn install v1.5.1

info No lockfile found.

[1/5] Validating package.json...

[2/5] Resolving packages...

[3/5] Fetching packages...

info fsevents@1.1.3: The platform "win32" is incompatible with this module.

info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.

[4/5] Linking dependencies...
```

- final status
```
Congratulations

Congratulations! Your Project "aurelia-app" Has Been Created!

Getting started

Now it's time for you to get started. It's easy. First, change
directory into your new project's folder. You can use cd aurelia-app to get there. Once in
your project folder, simply run your new app with au run. Your app will run fully bundled. If
you would like to have it auto-refresh whenever you make changes to your HTML, JavaScript or CSS, simply use the --watch flag If you want to build your app for production, run au build --env prod.
That's just about all there is to it. If you need help, simply run au help.


Happy Coding!
```

Used **`au run`** to execute this `aurelia-app`:
```
 au run
Starting 'configureEnvironment'...
Finished 'configureEnvironment'
Starting 'runWebpack'...
(node:16556) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Project is running at http://localhost:8080
webpack output is served from /
Content not from webpack is served from c:\work\learning\cli\typescript-webpack\aurelia-app\dist
404s will fallback to /index.html
Finished 'runWebpack'
Hash: 9d6e4a7bdf7e930d2241
Version: webpack 4.4.1
Time: 4565ms
Built at: 2018-3-30 13:51:26
                                Asset       Size  Chunks                    Chunk Names
   app.9d6e4a7bdf7e930d2241.bundle.js   2.35 MiB     app  [emitted]  [big]  app
vendor.9d6e4a7bdf7e930d2241.bundle.js    489 KiB  vendor  [emitted]  [big]  vendor
                           index.html  589 bytes          [emitted]
Entrypoint app [big] = app.9d6e4a7bdf7e930d2241.bundle.js
Entrypoint vendor [big] = vendor.9d6e4a7bdf7e930d2241.bundle.js
[./node_modules/aurelia-bootstrapper/dist/native-modules/aurelia-bootstrapper.js] 5.17 KiB {app} [built]
[./node_modules/aurelia-loader-webpack/dist/native-modules/aurelia-loader-webpack.js] 14.4 KiB {app} [built]
[./node_modules/aurelia-pal/dist/native-modules/aurelia-pal.js] 2.18 KiB {app} [built]
[./node_modules/aurelia-polyfills/dist/native-modules/aurelia-polyfills.js] 24.4 KiB {app} [built]
[./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js] 585 bytes {app} [built]
[./node_modules/aurelia-webpack-plugin/runtime/pal-loader-entry.js] 1.56 KiB {app} [built]
[./node_modules/bluebird/js/browser/bluebird.js] 175 KiB {vendor} {app} [built]
[./node_modules/bluebird/js/browser/bluebird.js-exposed] 65 bytes {vendor} {app} [built]
[./node_modules/process/browser.js] 5.29 KiB {vendor} {app} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {vendor} {app} [built]
[aurelia-framework] ./node_modules/aurelia-framework/dist/native-modules/aurelia-framework.js 14 KiB {app} [built]
[aurelia-pal-browser] ./node_modules/aurelia-pal-browser/dist/native-modules/aurelia-pal-browser.js 16.9 KiB {app} [built]
[main] ./src/main.ts 1.09 KiB {app} [built]
   [0] multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry aurelia-bootstrapper 52 bytes {app} [built]
   [1] multi bluebird 28 bytes {vendor} [built]
    + 65 hidden modules
Child html-webpack-plugin for "index.html":
         Asset      Size  Chunks  Chunk Names
    index.html  1.36 MiB       0
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./index.ejs] 1.03 KiB {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 519 bytes {0} [built]
```
- starting this app with `http://localhost:8080`

- The following text is **added** to my `cmder.exe` console

```
i ｢wdm｣: wait until bundle finished: /app.9d6e4a7bdf7e930d2241.bundle.js
i ｢wdm｣: wait until bundle finished: /vendor.9d6e4a7bdf7e930d2241.bundle.js
× ｢wdm｣: ConcurrentCompilationError: You ran Webpack twice. Each instance only supports a single concurrent compilation at a time.
    at Compiler.run (c:\work\learning\cli\typescript-webpack\aurelia-app\node_modules\webpack\lib\Compiler.js:149:37)
    at rebuild (c:\work\learning\cli\typescript-webpack\aurelia-app\node_modules\webpack-dev-middleware\lib\context.js:81:24)
    at done (c:\work\learning\cli\typescript-webpack\aurelia-app\node_modules\webpack-dev-middleware\lib\context.js:59:7)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (c:\work\learning\cli\typescript-webpack\aurelia-app\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:18:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (c:\work\learning\cli\typescript-webpack\aurelia-app\node_modules\tapable\lib\Hook.js:35:21)
    at emitRecords.err (c:\work\learning\cli\typescript-webpack\aurelia-app\node_modules\webpack\lib\Compiler.js:201:22)
    at Compiler.emitRecords (c:\work\learning\cli\typescript-webpack\aurelia-app\node_modules\webpack\lib\Compiler.js:313:39)
    at emitAssets.err (c:\work\learning\cli\typescript-webpack\aurelia-app\node_modules\webpack\lib\Compiler.js:195:10)
    at hooks.afterEmit.callAsync.err (c:\work\learning\cli\typescript-webpack\aurelia-app\node_modules\webpack\lib\Compiler.js:299:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (c:\work\learning\cli\typescript-webpack\aurelia-app\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (c:\work\learning\cli\typescript-webpack\aurelia-app\node_modules\tapable\lib\Hook.js:35:21)
    at asyncLib.forEach.err (c:\work\learning\cli\typescript-webpack\aurelia-app\node_modules\webpack\lib\Compiler.js:296:27)
    at done (c:\work\learning\cli\typescript-webpack\aurelia-app\node_modules\neo-async\async.js:2809:11)
    at c:\work\learning\cli\typescript-webpack\aurelia-app\node_modules\neo-async\async.js:2760:7
    at MemoryFileSystem.writeFile (c:\work\learning\cli\typescript-webpack\aurelia-app\node_modules\memory-fs\lib\MemoryFileSystem.js:328:9)
    at writeOut (c:\work\learning\cli\typescript-webpack\aurelia-app\node_modules\webpack\lib\Compiler.js:282:29)

- Chrome's console shows no errors (or any other indication:

![image](https://user-images.githubusercontent.com/2712405/38148245-9f2433cc-3423-11e8-9d97-0fbdef32cec2.png)

After sufficient time has expired, Chrome's console shows the standard "timeout" text:

```
GET http://localhost:8080/app.9d6e4a7bdf7e930d2241.bundle.js net::ERR_EMPTY_RESPONSE
localhost/:15 GET http://localhost:8080/vendor.9d6e4a7bdf7e930d2241.bundle.js net::ERR_EMPTY_RESPONSE
```

**Comment by Alexander-Taran** [comment]
webpack issue
tracked here https://github.com/aurelia/cli/issues/852 for cli 
and here https://github.com/webpack/webpack/issues/6825 for webpack

this one can be closed

**Comment by adriatic** [comment]
I agree - as I checked both references [above](https://github.com/aurelia/cli/issues/863#issuecomment-377623821).

Closing.
