### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by amar-muratovic** [aurelia/cli#889]
Starting 'readProjectConfiguration'...
{ uid: 2,
  name: 'readProjectConfiguration',
  branch: false,
  error: TypeError: Cannot read property 'indexOf' of undefined
    at exports.PackageAnalyzer.reverseEngineer (C:\Users\Amar.M\Desktop\blog-start\node_modules\aurelia-cli\lib\build\package-analyzer.js:22:27)
    at analyzeDependency (C:\Users\Amar.M\Desktop\blog-start\node_modules\aurelia-cli\lib\build\bundler.js:204:26)
    at exports.Bundler.configureDependency (C:\Users\Amar.M\Desktop\blog-start\node_modules\aurelia-cli\lib\build\bundler.js:129:12)
    at Utils.runSequentially.dep (C:\Users\Amar.M\Desktop\blog-start\node_modules\aurelia-cli\lib\build\bundle.js:43:24)
    at exec (C:\Users\Amar.M\Desktop\blog-start\node_modules\aurelia-cli\lib\build\utils.js:23:14)
    at <anonymous>,
  duration: [ 0, 17985518 ],
  time: 1528123612150 }
{ uid: 1,
  name: '<series>',
  branch: true,
  error: TypeError: Cannot read property 'indexOf' of undefined
    at exports.PackageAnalyzer.reverseEngineer (C:\Users\Amar.M\Desktop\blog-start\node_modules\aurelia-cli\lib\build\package-analyzer.js:22:27)
    at analyzeDependency (C:\Users\Amar.M\Desktop\blog-start\node_modules\aurelia-cli\lib\build\bundler.js:204:26)
    at exports.Bundler.configureDependency (C:\Users\Amar.M\Desktop\blog-start\node_modules\aurelia-cli\lib\build\bundler.js:129:12)
    at Utils.runSequentially.dep (C:\Users\Amar.M\Desktop\blog-start\node_modules\aurelia-cli\lib\build\bundle.js:43:24)
    at exec (C:\Users\Amar.M\Desktop\blog-start\node_modules\aurelia-cli\lib\build\utils.js:23:14)
    at <anonymous>,
  duration: [ 0, 31066050 ],
  time: 1528123612163 }
{ uid: 0,
  name: '<series>',
  branch: true,
  error: TypeError: Cannot read property 'indexOf' of undefined
    at exports.PackageAnalyzer.reverseEngineer (C:\Users\Amar.M\Desktop\blog-start\node_modules\aurelia-cli\lib\build\package-analyzer.js:22:27)
    at analyzeDependency (C:\Users\Amar.M\Desktop\blog-start\node_modules\aurelia-cli\lib\build\bundler.js:204:26)
    at exports.Bundler.configureDependency (C:\Users\Amar.M\Desktop\blog-start\node_modules\aurelia-cli\lib\build\bundler.js:129:12)
    at Utils.runSequentially.dep (C:\Users\Amar.M\Desktop\blog-start\node_modules\aurelia-cli\lib\build\bundle.js:43:24)
    at exec (C:\Users\Amar.M\Desktop\blog-start\node_modules\aurelia-cli\lib\build\utils.js:23:14)
    at <anonymous>,
  duration: [ 0, 34955400 ],
  time: 1528123612165 }
TypeError: Cannot read property 'indexOf' of undefined
    at exports.PackageAnalyzer.reverseEngineer (C:\Users\Amar.M\Desktop\blog-start\node_modules\aurelia-cli\lib\build\package-analyzer.js:22:27)
    at analyzeDependency (C:\Users\Amar.M\Desktop\blog-start\node_modules\aurelia-cli\lib\build\bundler.js:204:26)
    at exports.Bundler.configureDependency (C:\Users\Amar.M\Desktop\blog-start\node_modules\aurelia-cli\lib\build\bundler.js:129:12)
    at Utils.runSequentially.dep (C:\Users\Amar.M\Desktop\blog-start\node_modules\aurelia-cli\lib\build\bundle.js:43:24)
    at exec (C:\Users\Amar.M\Desktop\blog-start\node_modules\aurelia-cli\lib\build\utils.js:23:14)
    at <anonymous>

**Comment by avrahamcool** [comment]
please provide more details about your project configuration.
is it a CLI project? (what version of the cli, what option did you choose?)
`npm` or `yarn`?
verison of node..
are you running `au build` or `au run`? are you runing with `--watch`?
did you change the build/run tasks? or is it out of the box?

**Comment by JeroenVinke** [comment]
Closing this issue, please reopen with additional information about the issue
