### ISSUE TITLE
"au new" errors out, can't start a project.  Please help

### ISSUE THREAD

**Issue by tkvinfolio** [aurelia/cli#891]
**I'm submitting a bug report**

**Please tell us about your environment:**
* **Mac OSX 10.12.6 Sierra :**

* **Node Version:**
Now using node v8.11.3 (npm v5.6.0)

* **NPM Version:**
npm v5.6.0

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
ESNext

* **Loader/bundler:**
all | Webpack | SystemJS | RequireJS

**Current behavior:**
** "au new" errors out as: **
step 1:  installed aurelia-cli as : 
$ npm install aurelia-cli -g 
step2:  tried to create a new project as: 
$ au new
module.js:549
    throw err;
    ^
Error: Cannot find module 'aurelia-dependency-injection'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/tperiasa/.nvm/versions/node/v8.11.3/lib/node_modules/aurelia-cli/lib/cli.js:3:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
* **What is the expected behavior?**
Should create all skeleton aurelia scripts, templates, for development.  NOTHING available

**Comment by kladebo** [comment]
I'm having the same problems here..

internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module 'aurelia-dependency-injection'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Klaas\AppData\Roaming\npm\node_modules\aurelia-cli\lib\cli.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)

I updated the aurelia-cli this morning now it seems broken.
After updating everything else like: node, npm and all global packages it still gives me this error...

**Comment by ShauniArima** [comment]
Same problem for all `au` commands.

```sh
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module 'aurelia-dependency-injection'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/lib/node_modules/aurelia-cli/lib/cli.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
```

**Comment by marekpetak** [comment]
I can see the same error creating new project on Windows 10 Pro, Node 8.11.3, aurelia-cli 0.33.
Project will get created OK, but when runnin _au run --watch_
 I get same error

`	
        module.js:549
		throw err;
		^

	Error: Cannot find module 'aurelia-dependency-injection'
		at Function.Module._resolveFilename (module.js:547:15)
		at Function.Module._load (module.js:474:25)
		at Module.require (module.js:596:17)
		at require (internal/module.js:11:18)
		at Object.<anonymous> (E:\src_projects\Rennes\test2\node_modules\aurelia-cli\lib\cli.js:3:19)
		at Module._compile (module.js:652:30)
		at Object.Module._extensions..js (module.js:663:10)
		at Module.load (module.js:565:32)
		at tryModuleLoad (module.js:505:12)
		at Function.Module._load (module.js:497:3)
`

**Comment by gcastre** [comment]
Same problem here

**Comment by tkvinfolio** [comment]
thanks for the the hint on issue #166.  After installing dependency injection 1.4.1, as:
   "npm install -g aurelia-dependency-injection@1.4.1"
"au new" command successfully starts.

**Comment by tkvinfolio** [comment]
"npm install -g aurelia-dependency-injection@1.4.1"
"au new" command gives same error.

**Comment by tkvinfolio** [comment]
1. install "npm install -g aurelia-dependency-injection@^1.4.1"
2. install "npm install -g aurelia-cli"
These two steps seem to fire "au new" without error.
Will close it after verifying again.

**Comment by JeroenVinke** [comment]
This issue has been fixed in aurelia-dependency-injection. When I create a new app it works again
