### ISSUE TITLE
au new --here in .Net Core 2.1 project crashes during installing project dependencies

### ISSUE THREAD

**Issue by codermrrob** [aurelia/cli#895]
**I'm submitting a bug report**

* **Library Version:**
major.minor.patch-pre

**Please tell us about your environment:**
* **Operating System:**
Windows10Pro

* **Node Version:**
6.11.4

* **NPM Version:**
3.10.10

**Current behavior:**
`au new --here` running in a .Net Core 2.1 project folder.
cli crashes out during installing project dependencies. Happens with a variety of options.

`Would you like to install the project dependencies?

1. Yes (Default)
   Installs all server, client and tooling dependencies needed to build the project.
2. No
   Completes the new project wizard without installing dependencies.

[Yes]> 1

Installing project dependencies.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:195:12)
    at PassThrough.Writable.write (_stream_writable.js:242:5)
    at PassThrough.Writable.end (_stream_writable.js:479:10)
    at ReadEntry.entry.on (C:\Users\mrrob\AppData\Roaming\npm\node_modules\aurelia-cli\node_modules\npm\node_modules\pacote\lib\extract-stream.js:19:41)
    at emitOne (events.js:101:20)
    at ReadEntry.emit (events.js:188:7)
    at ReadEntry.emit (C:\Users\mrrob\AppData\Roaming\npm\node_modules\aurelia-cli\node_modules\npm\node_modules\tar\node_modules\minipass\index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (C:\Users\mrrob\AppData\Roaming\npm\node_modules\aurelia-cli\node_modules\npm\node_modules\tar\node_modules\minipass\index.js:249:12)
    at ReadEntry.end (C:\Users\mrrob\AppData\Roaming\npm\node_modules\aurelia-cli\node_modules\npm\node_modules\tar\node_modules\minipass\index.js:162:27)
    at Unpack.[consumeBody] (C:\Users\mrrob\AppData\Roaming\npm\node_modules\aurelia-cli\node_modules\npm\node_modules\tar\lib\parse.js:210:13)
    at Unpack.[consumeChunkSub] (C:\Users\mrrob\AppData\Roaming\npm\node_modules\aurelia-cli\node_modules\npm\node_modules\tar\lib\parse.js:391:40)
    at Unpack.[consumeChunk] (C:\Users\mrrob\AppData\Roaming\npm\node_modules\aurelia-cli\node_modules\npm\node_modules\tar\lib\parse.js:360:30)
    at Unzip.(anonymous function).on.chunk (C:\Users\mrrob\AppData\Roaming\npm\node_modules\aurelia-cli\node_modules\npm\node_modules\tar\lib\parse.js:291:59)
    at emitOne (events.js:96:13)
    at Unzip.emit (events.js:188:7)
    at Unzip.emit (C:\Users\mrrob\AppData\Roaming\npm\node_modules\aurelia-cli\node_modules\npm\node_modules\tar\node_modules\minipass\index.js:296:25)`

* **What is the expected behavior?**
Completion of installation.

**Comment by Alexander-Taran** [comment]
Why are node_modules recursive? does not seem right for npm 3+
could you reinstall node/npm as well as delete `C:\Users\mrrob\AppData\Roaming\npm\node_modules\`
and reinstall aurelia-cli ?

**Comment by zcaotica** [comment]
Same problem, I have completely removed node and reinstalled.
NODE: 10.6.0
NPM: 6.1.0
SO: W10Pro

My installation on AU is not under VS but standalone ("Web (Default)" platform). 
I also tried with all default option without success.

Thk
Zeta

**Comment by JeroenVinke** [comment]
https://github.com/npm/npm/issues/19989#issuecomment-391153745
