### ISSUE TITLE
Error: Unhandled "error" event. ([object Object]) in some cases

### ISSUE THREAD

**Issue by ricardograca** [aurelia/cli#924]
**I'm submitting a bug report**

* **Library Version:**
0.35.1

**Please tell us about your environment:**
* **Operating System:**
Ubuntu 16.04.5

* **Node Version:**
8.9.3

* **NPM Version:**
6.1.0

* **Browser:**
all

* **Language:**
ESNext

* **Loader/bundler:**
SystemJS

**Current behavior:**

I've renamed all environments to their more verbose counterparts: `dev` -> `development`, etc.
If I don't specify an environment name when attempting to run any command this results in the following unrelated error message (example for `build`):

```
/home/ricardo/src/scratch-dashboard-ui/node_modules/async-done/index.js:18
    throw err;
    ^

Error: Unhandled "error" event. ([object Object])
    at Gulp.emit (events.js:186:19)
    at Object.error (/home/ricardo/src/scratch-dashboard-ui/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/home/ricardo/src/scratch-dashboard-ui/node_modules/now-and-later/lib/mapSeries.js:43:14)
    at f (/home/ricardo/src/scratch-dashboard-ui/node_modules/once/once.js:25:25)
    at f (/home/ricardo/src/scratch-dashboard-ui/node_modules/once/once.js:25:25)
    at tryCatch (/home/ricardo/src/scratch-dashboard-ui/node_modules/async-done/index.js:24:15)
    at done (/home/ricardo/src/scratch-dashboard-ui/node_modules/async-done/index.js:40:12)
    at Domain.onError (/home/ricardo/src/scratch-dashboard-ui/node_modules/async-done/index.js:51:5)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
```

* **What is the expected behavior?**

There should be a message explaining what the actual error is. It seems like currently all errors are eaten by this unhelpful error message. Possibly related with https://github.com/gulpjs/undertaker/issues/80.

**Comment by Alexander-Taran** [comment]
latest CLI does provide a meaningful error:
```
   { Error: File not found with singular glob: C:/Users/atara/repro/aurelia_project/environments/dev.js (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (C:\Users\atara\repro\node_modules\glob-stream\readable.js:84:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Glob.emit (events.js:211:7)
    at Glob._finish (C:\Users\atara\repro\node_modules\glob\glob.js:197:8)
    at done (C:\Users\atara\repro\node_modules\glob\glob.js:182:14)
    at Glob._processSimple2 (C:\Users\atara\repro\node_modules\glob\glob.js:688:12)
    at C:\Users\atara\repro\node_modules\glob\glob.js:676:10
    at Glob._stat2 (C:\Users\atara\repro\node_modules\glob\glob.js:772:12)
    at lstatcb_ (C:\Users\atara\repro\node_modules\glob\glob.js:764:12)
```
or you can modify your local CLI `cli-options.js`  line 35:
`  let env = this.getFlagValue('env') || process.env.NODE_ENV || 'dev';`

**Comment by Alexander-Taran** [comment]
@3cp can be closed
