### ISSUE TITLE
Error: Cannot find module 'aurelia-cli'

### ISSUE THREAD

**Issue by amitaibu** [aurelia/cli#99]
I have followed the README

1. `npm install aurelia-cli -g`
1. Cloned skeleton-navigation
1. Added [Aureliafile.js](https://github.com/aurelia/cli#configuration) in the root of the repo

upon `aurelia` I get this error:

```
warn: Local aurelia installation not found!

Error: Cannot find module 'aurelia-cli'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Library/WebServer/Documents/skeleton-navigation/Aureliafile.js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleCommands (/usr/local/share/npm/lib/node_modules/aurelia-cli/bin/aurelia.js:63:5)
    at Liftoff.<anonymous> (/usr/local/share/npm/lib/node_modules/aurelia-cli/node_modules/liftoff/index.js:196:12)
    at Liftoff.<anonymous> (/usr/local/share/npm/lib/node_modules/aurelia-cli/node_modules/liftoff/index.js:164:7)
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
```

**Comment by ahmedshuhel** [comment]
What is the command you tried to execute?  `aurelia bundle` ? Please note that some command needs a local installation.  For example `bundle` command. If you are using `skeleton-navigation`, do  `npm install aurelia-cli --save-dev` from inside your project. 

> A blog post is coming to explain how bundling works and how to configure it properly.  There will be a new release this week, the release update/change some of the bundling stuff. I would request you to use the next release instead for bundling.

**Comment by amitaibu** [comment]
> What is the command you tried to execute?

Just `aurelia`. but after the installing aurelia-cli locally it worked.
Should I create a PR to add `npm install aurelia-cli --save-dev` to the README?

> A blog post is coming to explain how bundling works and how to configure it properly.

Great, waiting for this to switch one of my apps to Aurelia :)

**Comment by ahmedshuhel** [comment]
> Should I create a PR to add npm install aurelia-cli --save-dev to the README?

We will update the README as part of the release. There are some other changes too.
